##########################################################################################
# oops/path/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops.path`.

The source types its methods in their docstrings rather than in their signatures, so the
type information for public symbols is published here instead. Only package stubs exist,
so a name is annotated when it is imported from the package that exports it and not when
it is imported from the module that defines it. The stub describes the shape of the API
exactly: every public name, its parameters, which of them are keyword-only, and which have
defaults. Types are given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any
from oops import (Body as Body, Event as Event, Fittable as Fittable, Frame as Frame,
                  Surface as Surface)
from oops.frame import FrameShift as FrameShift, SpiceFrame as SpiceFrame
from oops.cadence import TimeShift as TimeShift
from numpy import ndarray
from polymath import Scalar, Vector3
# Parameters documented as a polymath type are passed through `as_scalar` and its
# siblings, so each accepts the class, a number, or a nested sequence of numbers.
# `polymath.typedefs` names each of those unions.
from polymath.typedefs import ScalarLike, Vector3Like
from oops.mutable import Mutable as Mutable

__all__ = ['Path', 'NullPath', 'SSBPath', 'LinkedPath', 'RelativePath', 'ReversedPath',
           'RotatedPath', 'CirclePath', 'CoordPath', 'FixedPath', 'KeplerPath',
           'LinearCoordPath', 'LinearPath', 'MultiPath', 'PathShift', 'QuickPath',
           'SpicePath']

class Path(Mutable):
    @property
    def pickle_quickpath_details(self) -> bool: ...
    @pickle_quickpath_details.setter
    def pickle_quickpath_details(self, value: bool) -> None: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...
    def show(self, level: int, indent: int = 0) -> str: ...
    @property
    def waypoint(self) -> Path: ...
    @property
    def primary(self) -> Path: ...
    @property
    def origin(self) -> Path: ...
    @property
    def frame(self) -> Frame: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def path_id(self) -> str | None: ...
    @property
    def stripped_id(self) -> str | None: ...
    @property
    def string_id(self) -> str: ...
    @property
    def wrt_ssb(self) -> Path: ...
    @property
    def is_registered(self) -> bool: ...
    @staticmethod
    def as_path(path: Path | str) -> Path: ...
    @staticmethod
    def as_primary_path(path: Path | str) -> Path: ...
    @staticmethod
    def as_waypoint(path: Path | str) -> Path: ...
    @staticmethod
    def path_id_exists(path_id: str) -> bool: ...
    def subtract_from_event(self, event: Event, *, derivs: bool = True,
        quick: dict | bool | None = None) -> Event: ...
    def add_to_event(self, event: Event, *, derivs: bool = True,
        quick: dict | bool | None = None) -> Event: ...
    def wrt(self, origin: Path | str, frame: Frame | str | None = None) -> Path: ...
    def quick_path(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Path: ...
    SSB: SSBPath
    def photon_from_event(self, departure: Event, *, derivs: bool = False,
        guess: ScalarLike | None = None, antimask: ndarray | bool | None = None,
        quick: dict | bool | None = None,
        converge: dict | None = None) -> tuple[Event, Event]: ...
    def photon_to_event(self, arrival: Event, *, derivs: bool = False,
        guess: ScalarLike | None = None, antimask: ndarray | bool | None = None,
        quick: dict | bool | None = None,
        converge: dict | None = None) -> tuple[Event, Event]: ...

class NullPath(Path):
    def __init__(self, path: Path | str, frame: Frame | str | None = None) -> None: ...
    def event_at_time(self,
        time: ScalarLike, *, quick: dict | bool | None = False) -> Event: ...

class SSBPath(NullPath):
    def __new__(cls) -> SSBPath: ...
    def __init__(self) -> None: ...
    def __reduce__(self) -> Any: ...
    @property
    def string_id(self) -> str: ...

class LinkedPath(Path):
    def __init__(self, path: Path | str, parent: Path | str) -> None: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...

class RelativePath(Path):
    def __init__(self, path: Path | str, origin: Path | str) -> None: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...

class ReversedPath(Path):
    def __init__(self, path: Path | str) -> None: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...

class RotatedPath(Path):
    def __init__(self, path: Path | str, frame: Frame | str) -> None: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...

class CirclePath(Path):
    def __init__(self, radius: ScalarLike, lon: ScalarLike,
        rate: ScalarLike, epoch: ScalarLike,
        origin: Path | str, *, frame: Frame | str | None = None,
        path_id: str | None = None) -> None: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...

class CoordPath(Path):
    def __init__(self, surface: Surface, coords: tuple[ScalarLike, ...] | tuple, *,
        obs: Path | str | None = None, path_id: str | None = None) -> None: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...

class FixedPath(Path):
    def __init__(self, pos: Vector3Like, origin: Path | str,
        frame: Frame | str | None = None, *, path_id: str | None = None) -> None: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...

class KeplerPath(Path, Fittable):
    nparams: int
    def __init__(self, body: Body | str, epoch: float,
        elements: ndarray | dict | None = None, observer: Path | str | None = None, *,
        wobbles: str | tuple = (), path_id: str | None = None) -> None: ...
    def set_elements(self, elements: ndarray) -> None: ...
    def get_elements(self) -> ndarray: ...
    @property
    def params(self) -> tuple[float, ...]: ...
    def copy(self) -> KeplerPath: ...
    def event_at_time(self, time: ScalarLike, *, quick: dict | bool | None = None,
        partials: bool = False) -> Event: ...
    def node_at_time(self, time: ScalarLike) -> Scalar: ...
    def pole_at_time(self, time: ScalarLike) -> Vector3: ...
    def photon_to_event(self, arrival: Event, *, derivs: bool = False,
        guess: ScalarLike | None = None, antimask: ndarray | bool | None = None,
        quick: dict | bool | None = None, converge: dict | None = None,
        partials: bool = False) -> tuple[Event, Event]: ...

class LinearCoordPath(Path):
    def __init__(self, surface: Surface, coords: tuple, coords_dot: tuple,
        epoch: ScalarLike, *, obs: Path | str | None = None,
        path_id: str | None = None) -> None: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...

class LinearPath(Path):
    def __init__(self, pos: Vector3Like, epoch: ScalarLike,
        origin: Path | str, *, frame: Frame | str | None = None,
        path_id: str | None = None) -> None: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...

class MultiPath(Path):
    def __init__(self, paths: list[Path | str], origin: Path | str | None = None,
        frame: Frame | str | None = None, *, path_id: str | None = None) -> None: ...
    def __getitem__(self, i: int | slice) -> Path | MultiPath: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...
    def quick_path(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> MultiPath: ...

class PathShift(Path, Fittable):
    def __init__(self, arg: float | PathShift | FrameShift | TimeShift, /,
        path: Path | str, *, path_id: str | None = None,
        freeze: bool = False) -> None: ...
    @property
    def dt(self) -> float: ...
    @property
    def link(self) -> PathShift | FrameShift | TimeShift | None: ...
    nparams: int
    @property
    def params(self) -> tuple[float]: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...

class QuickPath(Path):
    def __init__(self, path: Path, tmin: float, tmax: float, quickdict: dict) -> None: ...
    def event_at_time(self,
        time: ScalarLike, *, quick: dict | bool | None = False) -> Event: ...
    def extend(self, tmin: float, tmax: float) -> None: ...
    @staticmethod
    def for_path(path: Path, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Path: ...

class SpicePath(Path):
    def __init__(self, spice_path: str | int, origin: SpicePath | str | None = None,
        frame: SpiceFrame | str | None = None, *, path_id: str | None = None) -> None: ...
    def event_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Event: ...
    @staticmethod
    def get(spice_path: SpicePath | str | int, origin: SpicePath | str | None = None,
        frame: SpiceFrame | str | None = None, *,
        path_id: str | None = None) -> SpicePath: ...

##########################################################################################
