##########################################################################################
# oops/path/path_.pyi
##########################################################################################
"""Type stub for :mod:`oops.path.path_`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. The stub describes the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

from ._photon_solver import (photon_from_event as photon_from_event,
                             photon_to_event as photon_to_event)
from oops._cache import _Cache as _Cache
from oops.config import PICKLE_CONFIG as PICKLE_CONFIG
from oops.event import Event as Event
from oops.frame.frame_ import Frame as Frame, J2000Frame as J2000Frame
from oops.frame.spiceframe import SpiceFrame as SpiceFrame
from oops.mutable import Mutable as Mutable

class Path(Mutable):
    @property
    def pickle_quickpath_details(self) -> Any: ...
    @pickle_quickpath_details.setter
    def pickle_quickpath_details(self, value: Any) -> None: ...
    def event_at_time(self, time: Any, *, quick: Any = None) -> Any: ...
    def show(self, level: Any, indent: int = 0) -> Any: ...
    @property
    def waypoint(self) -> Any: ...
    @property
    def primary(self) -> Any: ...
    @property
    def origin(self) -> Any: ...
    @property
    def frame(self) -> Any: ...
    @property
    def shape(self) -> Any: ...
    @property
    def path_id(self) -> Any: ...
    @property
    def stripped_id(self) -> Any: ...
    @property
    def string_id(self) -> Any: ...
    @property
    def wrt_ssb(self) -> Any: ...
    @property
    def is_registered(self) -> Any: ...
    @staticmethod
    def as_path(path: Any) -> Any: ...
    @staticmethod
    def as_primary_path(path: Any) -> Any: ...
    @staticmethod
    def as_waypoint(path: Any) -> Any: ...
    @staticmethod
    def path_id_exists(path_id: Any) -> Any: ...
    def subtract_from_event(self, event: Any, *, derivs: bool = True,
        quick: Any = None) -> Any: ...
    def add_to_event(self, event: Any, *, derivs: bool = True,
        quick: Any = None) -> Any: ...
    def wrt(self, origin: Any, frame: Any = None) -> Any: ...
    def quick_path(self, time: Any, *, quick: Any = None) -> Any: ...
    SSB: SSBPath
    def photon_from_event(self, departure: Any, *, derivs: bool = False,
        guess: Any = None, antimask: Any = None, quick: Any = None,
        converge: Any = None) -> Any: ...
    def photon_to_event(self, arrival: Any, *, derivs: bool = False, guess: Any = None,
        antimask: Any = None, quick: Any = None, converge: Any = None) -> Any: ...
class NullPath(Path):
    def __init__(self, path: Any, frame: Any = None) -> None: ...
    def event_at_time(self, time: Any, *, quick: bool = False) -> Any: ...
class SSBPath(NullPath):
    def __new__(cls) -> Any: ...
    def __init__(self) -> None: ...
    def __reduce__(self) -> Any: ...
    @property
    def string_id(self) -> Any: ...
class LinkedPath(Path):
    def __init__(self, path: Any, parent: Any) -> None: ...
    def event_at_time(self, time: Any, *, quick: Any = None) -> Any: ...
class RelativePath(Path):
    def __init__(self, path: Any, origin: Any) -> None: ...
    def event_at_time(self, time: Any, *, quick: Any = None) -> Any: ...
class ReversedPath(Path):
    def __init__(self, path: Any) -> None: ...
    def event_at_time(self, time: Any, *, quick: Any = None) -> Any: ...
class RotatedPath(Path):
    def __init__(self, path: Any, frame: Any) -> None: ...
    def event_at_time(self, time: Any, *, quick: Any = None) -> Any: ...

##########################################################################################
