##########################################################################################
# spicedb/__init__.pyi
##########################################################################################
"""Type stub for :mod:`spicedb`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. Only package stubs exist, so a name is annotated when it is
imported from the package that exports it and not when it is imported from the module
that defines it. The stub describes the shape of the API exactly: every public name, its
parameters, which of them are keyword-only, and which have defaults. Types are given
where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any
from filecache import FCPath as FCPath

__all__ = ['lrange', 'KernelInfo', 'kernels_from_filespec', 'set_spice_path',
           'get_spice_path', 'get_spice_filecache', 'get_spice_filecache_prefix',
           'open_db', 'close_db', 'db_is_open', 'set_translator', 'select_lsk',
           'select_pck', 'select_spk', 'select_inst', 'select_ck', 'select_by_name',
           'select_by_filespec', 'as_dict', 'furnish_kernels', 'furnish_lsk',
           'furnish_pck', 'furnish_spk', 'furnish_inst', 'furnish_ck', 'furnish_by_name',
           'furnish_by_metafile', 'furnish_by_filepath', 'unload_by_name',
           'unload_by_type', 'unload_by_filepath', 'unload_all', 'as_names',
           'furnished_names', 'furnished_basenames', 'used_basenames',
           'furnish_cassini_kernels', 'furnish_solar_system']

def lrange(*args: Any) -> Any: ...

class KernelInfo:
    kernel_name: Any
    kernel_version: Any
    kernel_type: Any
    filespec: Any
    start_time: Any
    stop_time: Any
    release_date: Any
    spice_id: Any
    load_priority: Any
    basename: Any
    start_tai: Any
    stop_tai: Any
    start_tdb: Any
    stop_tdb: Any
    file_no: Any
    def __init__(self, info: list | tuple) -> None: ...
    def compare(self, other: Any) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    @property
    def full_name(self) -> Any: ...
    @property
    def timeless(self) -> Any: ...

def kernels_from_filespec(filespec: Any, name: Any = None, version: Any = None,
    release: Any = None, priority: int = 100) -> Any: ...

def set_spice_path(spice_path: str = '') -> None: ...

def get_spice_path() -> Any: ...

def get_spice_filecache() -> Any: ...

def get_spice_filecache_prefix() -> Any: ...

def open_db(name: Any = None) -> None: ...

def close_db() -> None: ...

def db_is_open() -> Any: ...

def set_translator(func: Any) -> None: ...

def select_lsk(asof: str | None = None, after: str | None = None,
    redo: bool = True) -> list: ...

def select_pck(bodies: int | list | tuple | None = None, name: str | None = None,
    asof: str | None = None, after: str | None = None, redo: bool = True) -> list: ...

def select_spk(bodies: int | list | tuple, name: str | None = None,
    time: tuple | None = None, asof: str | None = None, after: str | None = None,
    redo: bool = True) -> list: ...

def select_inst(ids: int | list | tuple, inst: str | list | tuple | None = None,
    types: str | list | tuple | None = None, asof: str | None = None,
    after: str | None = None, redo: bool = True) -> list: ...

def select_ck(ids: int | list | tuple, name: str | None = None, time: tuple | None = None,
    asof: str | None = None, after: str | None = None, redo: bool = True) -> list: ...

def select_by_name(names: list, time: tuple | None = None) -> Any: ...

def select_by_filespec(filespecs: Any, time: tuple | None = None) -> Any: ...

def as_dict(kernel_list: Any) -> Any: ...

def furnish_kernels(kernel_list: Any, fast: bool = True) -> list: ...

def furnish_lsk(asof: str | None = None, after: str | None = None, redo: bool = True,
    fast: bool = True) -> list: ...

def furnish_pck(bodies: int | list | tuple | None = None, name: str | None = None,
    asof: str | None = None, after: str | None = None, redo: bool = True,
    fast: bool = True) -> list: ...

def furnish_spk(bodies: int | list | tuple, name: str | None = None,
    time: tuple | None = None, asof: str | None = None, after: str | None = None,
    redo: bool = True, fast: bool = True) -> list: ...

def furnish_inst(ids: int | list | tuple, inst: str | list | tuple | None = None,
    types: str | list | tuple | None = None, asof: str | None = None,
    after: str | None = None, redo: bool = True, fast: bool = True) -> list: ...

def furnish_ck(ids: int | list | tuple, name: str | None = None,
    time: tuple | None = None, asof: str | None = None, after: str | None = None,
    redo: bool = True, fast: bool = True) -> list: ...

def furnish_by_name(names: list, time: tuple | None = None,
    fast: bool = True) -> list: ...

def furnish_by_metafile(metafile: str | FCPath, time: tuple | None = None,
    asof: str | None = None) -> list: ...

def furnish_by_filepath(filepath: Any) -> None: ...

def unload_by_name(names: Any) -> None: ...

def unload_by_type(types: Any = None) -> None: ...

def unload_by_filepath(filepath: Any) -> None: ...

def unload_all() -> None: ...

def as_names(kernels: Any) -> Any: ...

def furnished_names(types: Any = None) -> Any: ...

def furnished_basenames(types: Any = None) -> Any: ...

def used_basenames(types: Any = [], time: Any = None, bodies: Any = [], sc: Any = None,
    inst: Any = None, slop: Any = ...) -> Any: ...

def furnish_cassini_kernels(start_time: str, stop_time: str,
    instrument: list | None = None, asof: str | None = None) -> list: ...

def furnish_solar_system(start_time: str | None = None, stop_time: str | None = None,
    asof: str | None = None,
    planets: int | tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9)) -> list: ...

##########################################################################################
