##########################################################################################
# oops/lightsource/_CONSTELLATIONS.py
##########################################################################################

# From https://archive.aavso.org/constellation-names-and-abbreviations

_CONSTELLATIONS = [
    # Nominative            Genitive               Abbrev
    ('Andromeda',           'Andromedae',          'And'),
    ('Antlia',              'Antliae',             'Ant'),
    ('Apus',                'Apodis',              'Aps'),
    ('Aquarius',            'Aquarii',             'Aqr'),
    ('Aquila',              'Aquilae',             'Aql'),
    ('Ara',                 'Arae',                'Ara'),
    ('Aries',               'Arietis',             'Ari'),
    ('Auriga',              'Aurigae',             'Aur'),
    ('Bootes',              'Bootis',              'Boo'),
    ('Caelum',              'Caeli',               'Cae'),
    ('Camelopardalis',      'Camelopardalis',      'Cam'),
    ('Cancer',              'Cancri',              'Cnc'),
    ('Canes Venatici',      'Canum Venaticorum',   'CVn'),
    ('Canis Major',         'Canis Majoris',       'CMa'),
    ('Canis Minor',         'Canis Minoris',       'CMi'),
    ('Capricornus',         'Capricorni',          'Cap'),
    ('Carina',              'Carinae',             'Car'),
    ('Cassiopeia',          'Cassiopeiae',         'Cas'),
    ('Centaurus',           'Centauri',            'Cen'),
    ('Cepheus',             'Cephei',              'Cep'),
    ('Cetus',               'Ceti',                'Cet'),
    ('Chamaeleon',          'Chamaeleontis',       'Cha'),
    ('Circinus',            'Circini',             'Cir'),
    ('Columba',             'Columbae',            'Col'),
    ('Coma Berenices',      'Comae Berenices',     'Com'),
    ('Corona Australis',    'Coronae Australis',   'CrA'),
    ('Corona Borealis',     'Coronae Borealis',    'CrB'),
    ('Corvus',              'Corvi',               'Crv'),
    ('Crater',              'Crateris',            'Crt'),
    ('Crux',                'Crucis',              'Cru'),
    ('Cygnus',              'Cygni',               'Cyg'),
    ('Delphinus',           'Delphini',            'Del'),
    ('Dorado',              'Doradus',             'Dor'),
    ('Draco',               'Draconis',            'Dra'),
    ('Equuleus',            'Equulei',             'Equ'),
    ('Eridanus',            'Eridani',             'Eri'),
    ('Fornax',              'Fornacis',            'For'),
    ('Gemini',              'Geminorum',           'Gem'),
    ('Grus',                'Gruis',               'Gru'),
    ('Hercules',            'Herculis',            'Her'),
    ('Horologium',          'Horologii',           'Hor'),
    ('Hydra',               'Hydrae',              'Hya'),
    ('Hydrus',              'Hydri',               'Hyi'),
    ('Indus',               'Indi',                'Ind'),
    ('Lacerta',             'Lacertae',            'Lac'),
    ('Leo',                 'Leonis',              'Leo'),
    ('Leo Minor',           'Leonis Minoris',      'LMi'),
    ('Lepus',               'Leporis',             'Lep'),
    ('Libra',               'Librae',              'Lib'),
    ('Lupus',               'Lupi',                'Lup'),
    ('Lynx',                'Lyncis',              'Lyn'),
    ('Lyra',                'Lyrae',               'Lyr'),
    ('Mensa',               'Mensae',              'Men'),
    ('Microscopium',        'Microscopii',         'Mic'),
    ('Monoceros',           'Monocerotis',         'Mon'),
    ('Musca',               'Muscae',              'Mus'),
    ('Norma',               'Normae',              'Nor'),
    ('Octans',              'Octantis',            'Oct'),
    ('Ophiuchus',           'Ophiuchi',            'Oph'),
    ('Orion',               'Orionis',             'Ori'),
    ('Pavo',                'Pavonis',             'Pav'),
    ('Pegasus',             'Pegasi',              'Peg'),
    ('Perseus',             'Persei',              'Per'),
    ('Phoenix',             'Phoenicis',           'Phe'),
    ('Pictor',              'Pictoris',            'Pic'),
    ('Pisces',              'Piscium',             'Psc'),
    ('Piscis Austrinus',    'Piscis Austrini',     'PsA'),
    ('Puppis',              'Puppis',              'Pup'),
    ('Pyxis',               'Pyxidis',             'Pyx'),
    ('Reticulum',           'Reticuli',            'Ret'),
    ('Sagitta',             'Sagittae',            'Sge'),
    ('Sagittarius',         'Sagittarii',          'Sgr'),
    ('Scorpius',            'Scorpii',             'Sco'),
    ('Sculptor',            'Sculptoris',          'Scl'),
    ('Scutum',              'Scuti',               'Sct'),
    ('Serpens',             'Serpentis',           'Ser'),
    ('Sextans',             'Sextantis',           'Sex'),
    ('Taurus',              'Tauri',               'Tau'),
    ('Telescopium',         'Telescopii',          'Tel'),
    ('Triangulum',          'Trianguli',           'Tri'),
    ('Triangulum Australe', 'Trianguli Australis', 'TrA'),
    ('Tucana',              'Tucanae',             'Tuc'),
    ('Ursa Major',          'Ursae Majoris',       'UMa'),
    ('Ursa Minor',          'Ursae Minoris',       'UMi'),
    ('Vela',                'Velorum',             'Vel'),
    ('Virgo',               'Virginis',            'Vir'),
    ('Volans',              'Volantis',            'Vol'),
    ('Vulpecula',           'Vulpeculae',          'Vul'),
]

_CONSTELLATION_ABBREVS = {name: abbrev for _, name, abbrev in _CONSTELLATIONS}

##########################################################################################
