##########################################################################################
# oops/surface/graphicellipsoid.pyi
##########################################################################################
"""Type stub for :mod:`oops.surface.graphicellipsoid`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. The stub describes the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

from oops.surface.ellipsoid import Ellipsoid as Ellipsoid

class GraphicEllipsoid(Ellipsoid):
    def coords_from_vector3(self, pos: Any, *, obs: Any = None, time: Any = None,
        axes: int = 2, derivs: bool = False, hints: Any = None,
        groundtrack: bool = False) -> Any: ...
    def vector3_from_coords(self, coords: Any, *, obs: Any = None, time: Any = None,
        derivs: bool = False, hints: Any = None, groundtrack: bool = False) -> Any: ...
    def lon_to_centric(self, lon: Any, *, derivs: bool = False) -> Any: ...
    def lon_from_centric(self, lon: Any, *, derivs: bool = False) -> Any: ...
    def lon_to_graphic(self, lon: Any, *, derivs: bool = False) -> Any: ...
    def lon_from_graphic(self, lon: Any, *, derivs: bool = False) -> Any: ...
    def lat_to_centric(self, lat: Any, lon: Any, *, derivs: bool = False) -> Any: ...
    def lat_from_centric(self, lat: Any, lon: Any, *, derivs: bool = False) -> Any: ...
    def lat_to_graphic(self, lat: Any, lon: Any, *, derivs: bool = False) -> Any: ...
    def lat_from_graphic(self, lat: Any, lon: Any, *, derivs: bool = False) -> Any: ...

##########################################################################################
