##########################################################################################
# oops/frame/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops.frame`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. Only package stubs exist, so a name is annotated when it is
imported from the package that exports it and not when it is imported from the module
that defines it. The stub describes the shape of the API exactly: every public name, its
parameters, which of them are keyword-only, and which have defaults. Types are given
where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any
from oops.path import KeplerPath as KeplerPath, PathShift as PathShift
from oops import Fittable as Fittable, Path as Path, Transform as Transform
from oops.cadence import TimeShift as TimeShift
from numpy import ndarray, number
from polymath import Matrix3, Scalar, Vector3
from oops.mutable import Mutable as Mutable

# Parameters documented as a polymath type are passed through `as_scalar` and its
# siblings, so each accepts the class, a number, or a nested sequence of numbers.
# `str` is excluded deliberately: no polymath constructor accepts one.
_Numeric = float | number | list['_Numeric'] | tuple['_Numeric', ...]
Matrix3Like = Matrix3 | ndarray | _Numeric
ScalarLike = Scalar | ndarray | _Numeric

Vector3Like = Vector3 | ndarray | _Numeric

__all__ = ['Frame', 'NullFrame', 'J2000Frame', 'LinkedFrame', 'ReversedFrame', 'Cmatrix',
           'FrameShift', 'InclinedFrame', 'LaplaceFrame', 'Navigation', 'PoleFrame',
           'PosTargFrame', 'QuickFrame', 'RingFrame', 'Rotation', 'SpiceFrame',
           'SpiceType1Frame', 'SpinFrame', 'SynchronousFrame', 'TrackerFrame',
           'TwoVectorFrame']

class Frame(Mutable):
    @property
    def pickle_quickframe_details(self) -> Any: ...
    @pickle_quickframe_details.setter
    def pickle_quickframe_details(self, value: Any) -> None: ...
    def transform_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Transform: ...
    def transform_at_time_if_possible(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> tuple[Scalar, Transform]: ...
    def node_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Scalar: ...
    def show(self, level: int, indent: int = 0) -> str: ...
    @property
    def wayframe(self) -> Any: ...
    @property
    def primary(self) -> Any: ...
    @property
    def reference(self) -> Any: ...
    @property
    def origin(self) -> Any: ...
    @property
    def is_inertial(self) -> Any: ...
    @property
    def shape(self) -> Any: ...
    @property
    def frame_id(self) -> Any: ...
    @property
    def stripped_id(self) -> Any: ...
    @property
    def string_id(self) -> Any: ...
    @property
    def wrt_j2000(self) -> Any: ...
    @property
    def is_registered(self) -> Any: ...
    @staticmethod
    def as_frame(frame: Frame | str) -> Frame: ...
    @staticmethod
    def as_primary_frame(frame: Frame | str) -> Frame: ...
    @staticmethod
    def as_wayframe(frame: Frame | str) -> Frame: ...
    @staticmethod
    def frame_id_exists(frame_id: str) -> bool: ...
    def wrt(self, reference: Frame | str) -> Frame: ...
    def quick_frame(self, time: ScalarLike | tuple, *,
        quick: dict | bool | None = None) -> Frame: ...
    J2000: Any

class NullFrame(Frame):
    def __init__(self, frame: Frame | str) -> None: ...
    def transform_at_time(self,  # type: ignore[override]
        time: ScalarLike, *, quick: bool = False) -> Transform: ...

class J2000Frame(NullFrame):
    def __new__(cls) -> Any: ...
    def __init__(self) -> None: ...
    def __reduce__(self) -> Any: ...
    @property
    def string_id(self) -> Any: ...

class LinkedFrame(Frame):
    def __init__(self, frame: Frame | str, parent: Frame | str) -> None: ...
    def transform_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Transform: ...
    def transform_at_time_if_possible(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> tuple[Scalar, Transform]: ...

class ReversedFrame(Frame):
    def __init__(self, frame: Frame | str) -> None: ...
    def transform_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Transform: ...
    def transform_at_time_if_possible(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> tuple[Scalar, Transform]: ...

class Cmatrix(Frame):
    def __init__(self, cmatrix: Matrix3Like, reference: Frame | str | None = None, *,
        frame_id: str | None = None) -> None: ...
    @property
    def transform(self) -> Any: ...
    @staticmethod
    def from_ra_dec(ra: ScalarLike, dec: ScalarLike, clock: ScalarLike,
        reference: Frame | str | None = None, *,
        frame_id: str | None = None) -> Cmatrix: ...
    def transform_at_time(self,  # type: ignore[override]
        time: ScalarLike, *, quick: bool = False) -> Transform: ...

class FrameShift(Frame, Fittable):
    def __init__(self, arg: float | FrameShift | TimeShift | PathShift, /,
        frame: Frame | str, *, frame_id: str | None = None,
        freeze: bool = False) -> None: ...
    @property
    def dt(self) -> Any: ...
    @property
    def link(self) -> Any: ...
    nparams: int
    @property
    def params(self) -> Any: ...
    def transform_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Transform: ...

class InclinedFrame(Frame):
    def __init__(self, inc: ScalarLike, node: ScalarLike, rate: ScalarLike,
        epoch: ScalarLike, *, despin: bool = True, reference: Frame | str | None = None,
        frame_id: str | None = None) -> None: ...
    def transform_at_time(self,  # type: ignore[override]
        time: ScalarLike, *, quick: bool = False) -> Transform: ...
    def node_at_time(self,  # type: ignore[override]
        time: ScalarLike, *, quick: bool = False) -> Scalar: ...

class LaplaceFrame(Frame):
    def __init__(self, orbit: KeplerPath | str, tilt: float = 0.0, *,
        frame_id: str | None = None, cache_size: int = 100) -> None: ...
    def transform_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Transform: ...

class Navigation(Frame, Fittable):
    nparams: Any
    def __init__(self, arg: ndarray | Navigation, /, reference: Frame | str, *,
        freeze: bool = False, frame_id: str | None = None,
        _matrix: Matrix3Like | None = None) -> None: ...
    @property
    def angles(self) -> Any: ...
    @property
    def link(self) -> Any: ...
    @property
    def params(self) -> Any: ...
    def transform_at_time(self,  # type: ignore[override]
        time: ScalarLike, *, quick: bool = False) -> Transform: ...

class PoleFrame(Frame):
    def __init__(self, frame: Frame | str, pole: Vector3Like | ndarray, *,
        retrograde: bool = False, aries: bool = False, frame_id: str | None = None,
        cache_size: int = 100) -> None: ...
    def transform_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Transform: ...
    def node_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Scalar: ...

class PosTargFrame(Frame):
    def __init__(self, xpos: float, ypos: float, reference: Frame | str, *,
        frame_id: str | None = None) -> None: ...
    def transform_at_time(self,  # type: ignore[override]
        time: ScalarLike, *, quick: bool = False) -> Transform: ...

class QuickFrame(Frame):
    def __init__(self, frame: Frame | str, tmin: float, tmax: float,
        quick: dict | bool | None = None) -> None: ...
    def transform_at_time(self,  # type: ignore[override]
        time: ScalarLike, *, quick: bool = False) -> Transform: ...
    def extend(self, tmin: float, tmax: float) -> None: ...
    @staticmethod
    def for_frame(frame: Frame, time: ScalarLike | tuple, *,
        quick: dict | bool | None = None) -> Frame: ...

class RingFrame(Frame):
    def __init__(self, frame: Frame | str, epoch: ScalarLike | float | None = None, *,
        aries: bool = False, retrograde: bool = False, frame_id: str | None = None,
        cache_size: int = 100) -> None: ...
    def transform_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Transform: ...
    def node_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Scalar: ...

class Rotation(Frame, Fittable):
    def __init__(self, arg: ScalarLike | ndarray | float | Rotation, /, axis: int | str,
        reference: Frame | str, *, freeze: bool = False,
        frame_id: str | None = None) -> None: ...
    @property
    def angle(self) -> Any: ...
    nparams: int
    @property
    def params(self) -> Any: ...
    def transform_at_time(self,  # type: ignore[override]
        time: ScalarLike, *, quick: bool = False) -> Transform: ...

class SpiceFrame(Frame):
    def __init__(self, spice_frame: str | int, reference: SpiceFrame | str | None = None,
        *, omega_type: str = 'tabulated', omega_dt: float = 1.0,
        frame_id: str | None = None) -> None: ...
    def transform_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Transform: ...
    def transform_at_time_if_possible(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> tuple[Scalar, Transform]: ...
    @staticmethod
    def get(spice_frame: str | int | SpiceFrame,
        reference: SpiceFrame | str | None = None, *, omega_type: str = 'tabulated',
        omega_dt: float = 1.0, frame_id: str | None = None) -> SpiceFrame: ...

class SpiceType1Frame(SpiceFrame):
    def __init__(self, spice_frame: str | int, tick_tolerance: float | int | str,
        reference: SpiceFrame | str | None = None, *, frame_id: str | None = None,
        cache_size: int = 100) -> None: ...
    def transform_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Transform: ...
    def transform_at_time_if_possible(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> tuple: ...
    @staticmethod
    def get(spice_frame: str | int,  # type: ignore[override]
        tick_tolerance: float | int | str, reference: SpiceFrame | str | None = None, *,
        frame_id: str | None = None,
        cache_size: int | None = None) -> SpiceType1Frame: ...

class SpinFrame(Frame):
    def __init__(self, offset: ScalarLike | ndarray | float,
        rate: ScalarLike | ndarray | float, epoch: ScalarLike | ndarray | float,
        axis: int | str, reference: Frame | str, *,
        frame_id: str | None = None) -> None: ...
    def transform_at_time(self,  # type: ignore[override]
        time: ScalarLike, *, quick: bool = False) -> Transform: ...

class SynchronousFrame(Frame):
    def __init__(self, orbit_path: Path | str, planet_path: Path | str | None = None, *,
        frame_id: str | None = None) -> None: ...
    def transform_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Transform: ...

class TrackerFrame(Frame):
    def __init__(self, frame: Frame | str, target: Path | str, observer: Path | str,
        epoch: ScalarLike | ndarray | float, *, frame_id: str | None = None,
        cache_size: int = 100) -> None: ...
    def transform_at_time(self, time: ScalarLike, *,
        quick: dict | bool | None = None) -> Transform: ...

class TwoVectorFrame(Frame):
    def __init__(self, reference: Frame | str, vector1: Vector3Like | ndarray,
        axis1: int | str, vector2: Vector3Like | ndarray, axis2: int | str, *,
        frame_id: str | None = None) -> None: ...
    def transform_at_time(self,  # type: ignore[override]
        time: ScalarLike, *, quick: bool = False) -> Transform: ...
    def node_at_time(self,  # type: ignore[override]
        time: ScalarLike, *, quick: bool = False) -> Scalar: ...

##########################################################################################
