##########################################################################################
# oops/frame/frame_.pyi
##########################################################################################
"""Type stub for :mod:`oops.frame.frame_`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. The stub describes the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

from oops.cache import Cache as Cache
from oops.config import PICKLE_CONFIG as PICKLE_CONFIG
from oops.mutable import Mutable as Mutable
from oops.transform import Transform as Transform

class Frame(Mutable):
    @property
    def pickle_quickframe_details(self) -> Any: ...
    @pickle_quickframe_details.setter
    def pickle_quickframe_details(self, value: Any) -> None: ...
    def transform_at_time(self, time: Any, *, quick: Any = None) -> Any: ...
    def transform_at_time_if_possible(self, time: Any, *, quick: Any = None) -> Any: ...
    def node_at_time(self, time: Any, *, quick: Any = None) -> Any: ...
    def show(self, level: Any, indent: int = 0) -> Any: ...
    @property
    def wayframe(self) -> Any: ...
    @property
    def primary(self) -> Any: ...
    @property
    def reference(self) -> Any: ...
    @property
    def origin(self) -> Any: ...
    @property
    def is_inertial(self) -> Any: ...
    @property
    def shape(self) -> Any: ...
    @property
    def frame_id(self) -> Any: ...
    @property
    def stripped_id(self) -> Any: ...
    @property
    def string_id(self) -> Any: ...
    @property
    def wrt_j2000(self) -> Any: ...
    @property
    def is_registered(self) -> Any: ...
    @staticmethod
    def as_frame(frame: Any) -> Any: ...
    @staticmethod
    def as_primary_frame(frame: Any) -> Any: ...
    @staticmethod
    def as_wayframe(frame: Any) -> Any: ...
    @staticmethod
    def frame_id_exists(frame_id: Any) -> Any: ...
    def wrt(self, reference: Any) -> Any: ...
    def quick_frame(self, time: Any, *, quick: Any = None) -> Any: ...
    J2000: J2000Frame
class NullFrame(Frame):
    def __init__(self, frame: Any) -> None: ...
    def transform_at_time(self, time: Any, *, quick: bool = False) -> Any: ...
class J2000Frame(NullFrame):
    def __new__(cls) -> Any: ...
    def __init__(self) -> None: ...
    def __reduce__(self) -> Any: ...
    @property
    def string_id(self) -> Any: ...
class LinkedFrame(Frame):
    def __init__(self, frame: Any, parent: Any) -> None: ...
    def transform_at_time(self, time: Any, *, quick: Any = None) -> Any: ...
    def transform_at_time_if_possible(self, time: Any, *, quick: Any = None) -> Any: ...
class ReversedFrame(Frame):
    def __init__(self, frame: Any) -> None: ...
    def transform_at_time(self, time: Any, *, quick: Any = None) -> Any: ...
    def transform_at_time_if_possible(self, time: Any, *, quick: Any = None) -> Any: ...

##########################################################################################
