##########################################################################################
# oops/cadence/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops.cadence`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. Only package stubs exist, so a name is annotated when it is
imported from the package that exports it and not when it is imported from the module
that defines it. The stub describes the shape of the API exactly: every public name, its
parameters, which of them are keyword-only, and which have defaults. Types are given
where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any
from oops.frame import FrameShift as FrameShift
from oops.path import PathShift as PathShift
from numpy import ndarray, number
from polymath import Boolean, Pair, Scalar
from oops import Fittable as Fittable
from oops.mutable import Mutable as Mutable

# Parameters documented as a polymath type are passed through `as_scalar` and its
# siblings, so each accepts the class, a number, or a nested sequence of numbers.
# `str` is excluded deliberately: no polymath constructor accepts one.
_Numeric = float | number | list['_Numeric'] | tuple['_Numeric', ...]
PairLike = Pair | ndarray | _Numeric
ScalarLike = Scalar | ndarray | _Numeric

__all__ = ['Cadence', 'DualCadence', 'Instant', 'Metronome', 'ReshapedCadence',
           'ReversedCadence', 'Sequence', 'SnapCadence', 'TDICadence', 'TimeShift']

class Cadence(Mutable):
    def time_at_tstep(self, tstep: ScalarLike | PairLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Scalar: ...
    def time_range_at_tstep(self, tstep: ScalarLike | PairLike, *, remask: bool = False,
        inclusive: bool = True, shift: bool = True) -> tuple[Scalar, Scalar]: ...
    def tstep_at_time(self, time: ScalarLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Scalar | Pair: ...
    def tstep_range_at_time(self, time: ScalarLike, *, remask: bool = False,
        inclusive: bool = True) -> tuple[Scalar | Pair, Scalar | Pair]: ...
    def time_is_outside(self, time: ScalarLike, *, inclusive: bool = True) -> Boolean: ...
    def time_shift(self, secs: float) -> Cadence: ...
    def as_continuous(self) -> Cadence: ...
    def time_is_inside(self, time: ScalarLike, *, inclusive: bool = True) -> Boolean: ...
    def tstride_at_tstep(self, tstep: ScalarLike | PairLike, sign: int = 1, *,
        remask: bool = False) -> Scalar | Pair: ...

class DualCadence(Cadence):
    shape: Any
    time: Any
    midtime: Any
    lasttime: Any
    is_continuous: Any
    is_unique: Any
    min_tstride: Any
    max_tstride: Any
    def __init__(self, long: Cadence, short: Cadence) -> None: ...
    def time_at_tstep(self,  # type: ignore[override]
        tstep: PairLike, *, remask: bool = False, derivs: bool = False,
        inclusive: bool = True) -> Scalar: ...
    def time_range_at_tstep(self,  # type: ignore[override]
        tstep: PairLike, *, remask: bool = False, inclusive: bool = True,
        shift: bool = True) -> tuple[Scalar, Scalar]: ...
    def tstep_at_time(self, time: ScalarLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Pair: ...
    def tstep_range_at_time(self, time: ScalarLike, *, remask: bool = False,
        inclusive: bool = True) -> tuple[Pair, Pair]: ...
    def time_is_outside(self, time: ScalarLike, *, inclusive: bool = True) -> Boolean: ...
    def time_shift(self, secs: float) -> DualCadence: ...
    def as_continuous(self) -> DualCadence: ...
    @staticmethod
    def for_array2d(samples: int, lines: int, tstart: float, texp: float,
        intersample_delay: float = 0.0,
        interline_delay: float | None = None) -> DualCadence: ...

class Instant(Cadence):
    shape: Any
    time: Any
    midtime: Any
    lasttime: Any
    is_continuous: bool
    is_unique: Any
    min_tstride: Any
    max_tstride: Any
    def __init__(self, tdb: ScalarLike) -> None: ...
    def time_at_tstep(self, tstep: ScalarLike | PairLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Scalar: ...
    def time_range_at_tstep(self, tstep: ScalarLike | PairLike, *, remask: bool = False,
        inclusive: bool = True, shift: bool = True) -> tuple[Scalar, Scalar]: ...
    def tstep_at_time(self, time: ScalarLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Scalar | Pair: ...
    def tstep_range_at_time(self, time: ScalarLike, *, remask: bool = False,
        inclusive: bool = True) -> tuple[Scalar | Pair, Scalar | Pair]: ...
    def time_is_outside(self, time: ScalarLike, *, inclusive: bool = True) -> Boolean: ...
    def time_shift(self, secs: float) -> Instant: ...
    def as_continuous(self) -> Instant: ...

class Metronome(Cadence):
    lasttime: Any
    time: Any
    midtime: Any
    shape: Any
    is_continuous: Any
    is_unique: Any
    min_tstride: Any
    max_tstride: Any
    def __init__(self, tstart: float, tstride: float, texp: float, steps: int, *,
        clip: bool = True) -> None: ...
    def time_at_tstep(self,  # type: ignore[override]
        tstep: ScalarLike, *, remask: bool = False, derivs: bool = False,
        inclusive: bool = True) -> Scalar: ...
    def time_range_at_tstep(self,  # type: ignore[override]
        tstep: ScalarLike, *, remask: bool = False, inclusive: bool = True,
        shift: bool = True) -> tuple[Scalar, Scalar]: ...
    def tstep_at_time(self, time: ScalarLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Scalar: ...
    def tstep_range_at_time(self, time: ScalarLike, *, remask: bool = False,
        inclusive: bool = True) -> tuple[Scalar, Scalar]: ...
    def time_is_outside(self, time: ScalarLike, *, inclusive: bool = True) -> Boolean: ...
    def time_shift(self, secs: float) -> Metronome: ...
    def as_continuous(self) -> Metronome: ...
    def tstride_at_tstep(self,  # type: ignore[override]
        tstep: ScalarLike, sign: int = 1, *, remask: bool = False) -> Scalar: ...
    @staticmethod
    def for_array1d(steps: int, tstart: float, texp: float,
        interstep_delay: float = 0.0) -> Metronome: ...

class ReshapedCadence(Cadence):
    shape: Any
    time: Any
    midtime: Any
    lasttime: Any
    is_continuous: Any
    is_unique: Any
    min_tstride: Any
    max_tstride: Any
    def __init__(self, cadence: Cadence, shape: tuple) -> None: ...
    def time_at_tstep(self, tstep: ScalarLike | PairLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Scalar: ...
    def time_range_at_tstep(self, tstep: ScalarLike | PairLike, *, remask: bool = False,
        inclusive: bool = True, shift: bool = True) -> tuple[Scalar, Scalar]: ...
    def tstep_at_time(self, time: ScalarLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Scalar | Pair: ...
    def tstep_range_at_time(self, time: ScalarLike, *, remask: bool = False,
        inclusive: bool = True) -> tuple[Scalar | Pair, Scalar | Pair]: ...
    def time_is_outside(self, time: ScalarLike, *, inclusive: bool = True) -> Boolean: ...
    def time_shift(self, secs: float) -> ReshapedCadence: ...
    def as_continuous(self) -> ReshapedCadence: ...

class ReversedCadence(Cadence):
    shape: Any
    lasttime: Any
    time: Any
    midtime: Any
    is_continuous: Any
    is_unique: Any
    min_tstride: Any
    max_tstride: Any
    def __init__(self, cadence: Cadence, axis: int = 0) -> None: ...
    def time_at_tstep(self,  # type: ignore[override]
        tstep: ScalarLike, *, remask: bool = False, derivs: bool = False,
        inclusive: bool = True) -> Scalar: ...
    def time_range_at_tstep(self,  # type: ignore[override]
        tstep: ScalarLike, *, remask: bool = False, inclusive: bool = True,
        shift: bool = True) -> tuple[Scalar, Scalar]: ...
    def tstep_at_time(self, time: ScalarLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Scalar: ...
    def tstep_range_at_time(self, time: ScalarLike, *, remask: bool = False,
        inclusive: bool = True) -> tuple[Scalar, Scalar]: ...
    def time_is_outside(self, time: ScalarLike, *, inclusive: bool = True) -> Boolean: ...
    def time_shift(self, secs: float) -> ReversedCadence: ...
    def as_continuous(self) -> ReversedCadence: ...

class Sequence(Cadence):
    min_tstride: Any
    max_tstride: Any
    is_continuous: Any
    is_unique: Any
    lasttime: Any
    time: Any
    midtime: Any
    shape: Any
    def __init__(self, tlist: ScalarLike | list | ndarray,
        texp: float | list | ndarray) -> None: ...
    def time_at_tstep(self,  # type: ignore[override]
        tstep: ScalarLike, *, remask: bool = False, derivs: bool = False,
        inclusive: bool = True) -> Scalar: ...
    def time_range_at_tstep(self,  # type: ignore[override]
        tstep: ScalarLike, *, remask: bool = False, inclusive: bool = True,
        shift: bool = True) -> tuple[Scalar, Scalar]: ...
    def tstep_at_time(self, time: ScalarLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Scalar: ...
    def tstep_range_at_time(self, time: ScalarLike, *, remask: bool = False,
        inclusive: bool = True) -> tuple[Scalar, Scalar]: ...
    def time_is_outside(self, time: ScalarLike, *, inclusive: bool = True) -> Boolean: ...
    def time_shift(self, secs: float) -> Sequence: ...
    def as_continuous(self) -> Sequence: ...

class SnapCadence(Metronome):
    def __init__(self, tstart: float, texp: float, *, clip: bool = True) -> None: ...

class TDICadence(Cadence):
    time: Any
    midtime: Any
    lasttime: Any
    shape: Any
    is_continuous: bool
    is_unique: Any
    min_tstride: float
    max_tstride: Any
    def __init__(self, lines: int, tstart: float, tdi_texp: float, tdi_stages: int,
        tdi_sign: int = -1) -> None: ...
    def tdi_shifts_at_line(self, line: ScalarLike, *, remask: bool = False,
        inclusive: bool = True, shift: bool = True) -> Scalar: ...
    def tdi_shifts_after_time(self, time: ScalarLike, *, remask: bool = False,
        inclusive: bool = True) -> Scalar: ...
    def time_at_tstep(self,  # type: ignore[override]
        tstep: ScalarLike, *, remask: bool = False, derivs: bool = False,
        inclusive: bool = True) -> Scalar: ...
    def time_range_at_tstep(self,  # type: ignore[override]
        tstep: ScalarLike, *, remask: bool = False, inclusive: bool = True,
        shift: bool = True) -> tuple[Scalar, Scalar]: ...
    def tstep_at_time(self, time: ScalarLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Scalar: ...
    def tstep_range_at_time(self, time: ScalarLike, *, remask: bool = False,
        inclusive: bool = True) -> tuple[Scalar, Scalar]: ...
    def time_is_outside(self, time: ScalarLike, *, inclusive: bool = True) -> Boolean: ...
    def time_shift(self, secs: float) -> TDICadence: ...
    def as_continuous(self) -> TDICadence: ...

class TimeShift(Cadence, Fittable):
    shape: Any
    is_continuous: Any
    is_unique: Any
    min_tstride: Any
    max_tstride: Any
    def __init__(self, arg: float | TimeShift | FrameShift | PathShift, /,
        cadence: Cadence) -> None: ...
    @property
    def dt(self) -> Any: ...
    @property
    def link(self) -> Any: ...
    nparams: int
    is_initialize: bool
    @property
    def params(self) -> Any: ...
    def time_at_tstep(self, tstep: ScalarLike | PairLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Scalar: ...
    def time_range_at_tstep(self, tstep: ScalarLike | PairLike, *, remask: bool = False,
        inclusive: bool = True, shift: bool = True) -> tuple[Scalar, Scalar]: ...
    def tstep_at_time(self, time: ScalarLike, *, remask: bool = False,
        derivs: bool = False, inclusive: bool = True) -> Scalar | Pair: ...
    def tstep_range_at_time(self, time: ScalarLike, *, remask: bool = False,
        inclusive: bool = True) -> tuple[Scalar | Pair, Scalar | Pair]: ...
    def time_is_outside(self, time: ScalarLike, *, inclusive: bool = True) -> Boolean: ...
    def time_shift(self, secs: float) -> TimeShift: ...
    def as_continuous(self) -> TimeShift: ...

##########################################################################################
