##########################################################################################
# oops/hosts/keck/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops.hosts.keck`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. Only package stubs exist, so a name is annotated when it is
imported from the package that exports it and not when it is imported from the module
that defines it. The stub describes the shape of the API exactly: every public name, its
parameters, which of them are keyword-only, and which have defaults. Types are given
where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

__all__ = ['from_file', 'Keck']

def from_file(filespec: Any, **parameters: Any) -> Any: ...

class Keck:
    def filespec(self, keck_file: Any) -> Any: ...
    def telescope_name(self, keck_file: Any) -> Any: ...
    def instrument_name(self, keck_file: Any) -> Any: ...
    def detector_name(self, keck_file: Any, **parameters: Any) -> Any: ...
    def data_array(self, keck_file: Any, **parameters: Any) -> Any: ...
    def time_limits(self, hst_file: Any, **parameters: Any) -> Any: ...
    def target_body(self, keck_file: Any) -> Any: ...
    def construct_snapshot(self, keck_file: Any, **parameters: Any) -> Any: ...
    @staticmethod
    def from_opened_fitsfile(keck_file: Any, **parameters: Any) -> Any: ...

##########################################################################################
