##########################################################################################
# oops/hosts/jwst/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops.hosts.jwst`.

The source types its methods in their docstrings rather than in their signatures, so the
type information for public symbols is published here instead. Only package stubs exist,
so a name is annotated when it is imported from the package that exports it and not when
it is imported from the module that defines it. The stub describes the shape of the API
exactly: every public name, its parameters, which of them are keyword-only, and which have
defaults. Types are given where they are unambiguous and are `Any` elsewhere.
"""

import pathlib
from typing import Any
from astropy.io.fits import HDUList
from filecache import FCPath as FCPath
from oops import Body, Cadence, Frame, Observation, Path
from oops.fov import WCSFOV
from oops.frame import PosTargFrame, TrackerFrame
from oops.path import LinearPath

__all__ = ['from_file', 'JWST']

def from_file(filespec: str | pathlib.Path | FCPath, **options: Any) -> Observation: ...

class JWST:
    def filespec(self, hdulist: HDUList, **options: Any) -> str: ...
    def basename(self, hdulist: HDUList, **options: Any) -> str: ...
    def telescope_name(self, hdulist: HDUList, **options: Any) -> str: ...
    def instrument_name(self, hdulist: HDUList, **options: Any) -> str: ...
    def header_subfields(self, hdulist: HDUList, **options: Any) -> dict[str, Any]: ...
    def check_options(self, options: dict[str, Any]) -> dict[str, Any]: ...
    def time_limits(self, hdulist: HDUList, **options: Any) -> tuple[float, float]: ...
    def row_cadence(self, hdulist: HDUList, **options: Any) -> Cadence: ...
    def jwst_path(self, hdulist: HDUList, **options: Any) -> LinearPath: ...
    def target_name(self, hdulist: HDUList, **options: Any) -> str: ...
    def target_body(self, hdulist: HDUList, **options: Any) -> Body: ...
    def tracker_frame(self, hdulist: HDUList, fov: WCSFOV, path: Path,
        **options: Any) -> TrackerFrame: ...
    def offset_frame(self, hdulist: HDUList, reference: Observation,
        **options: Any) -> PosTargFrame: ...
    def instrument_frame(self, hdulist: HDUList, fov: WCSFOV, path: Path,
        **options: Any) -> Frame: ...
    def iof_factor(self, hdulist: HDUList, path: Path, **options: Any) -> float: ...
    @staticmethod
    def from_hdulist(hdulist: HDUList, **options: Any) -> Observation: ...

INSTRUMENT_NAME: dict[str, str]

MASK_VALUES: dict[str, int]

RADIANS_PER_ARCSEC: float

##########################################################################################
