##########################################################################################
# oops/hosts/jwst/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops.hosts.jwst`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. Only package stubs exist, so a name is annotated when it is
imported from the package that exports it and not when it is imported from the module
that defines it. The stub describes the shape of the API exactly: every public name, its
parameters, which of them are keyword-only, and which have defaults. Types are given
where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any
from filecache import FCPath as FCPath
from oops import Path as Path

__all__ = ['from_file', 'JWST']

def from_file(filespec: str | Path | FCPath, **options: Any) -> Any: ...

class JWST:
    def filespec(self, hdulist: Any, **options: Any) -> Any: ...
    def basename(self, hdulist: Any, **options: Any) -> Any: ...
    def telescope_name(self, hdulist: Any, **options: Any) -> Any: ...
    def instrument_name(self, hdulist: Any, **options: Any) -> Any: ...
    def header_subfields(self, hdulist: Any, **options: Any) -> Any: ...
    def check_options(self, options: Any) -> Any: ...
    def time_limits(self, hdulist: Any, **options: Any) -> Any: ...
    def row_cadence(self, hdulist: Any, **options: Any) -> Any: ...
    def jwst_path(self, hdulist: Any, **options: Any) -> Any: ...
    def target_name(self, hdulist: Any, **options: Any) -> Any: ...
    def target_body(self, hdulist: Any, **options: Any) -> Any: ...
    def tracker_frame(self, hdulist: Any, fov: Any, path: Any, **options: Any) -> Any: ...
    def offset_frame(self, hdulist: Any, reference: Any, **options: Any) -> Any: ...
    def instrument_frame(self, hdulist: Any, fov: Any, path: Any,
        **options: Any) -> Any: ...
    def iof_factor(self, hdulist: Any, path: Any, **options: Any) -> Any: ...
    @staticmethod
    def from_hdulist(hdulist: Any, **options: Any) -> Any: ...

INSTRUMENT_NAME: dict[str, str]

MASK_VALUES: dict[str, int]

RADIANS_PER_ARCSEC: float

##########################################################################################
