##########################################################################################
# oops/hosts/hst/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops.hosts.hst`.

The source types its methods in their docstrings rather than in their signatures, so the
type information for public symbols is published here instead. Only package stubs exist,
so a name is annotated when it is imported from the package that exports it and not when
it is imported from the module that defines it. The stub describes the shape of the API
exactly: every public name, its parameters, which of them are keyword-only, and which have
defaults. Types are given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any
from pathlib import Path
from astropy.io.fits import HDUList, Header
from filecache import FCPath as FCPath
from numpy import ndarray
from oops import Body as Body, Calibration as Calibration, FOV as FOV, Frame as Frame
from oops.fov import FlatFOV as FlatFOV, PolynomialFOV as PolynomialFOV
from oops.observation import Snapshot as Snapshot
from tabulation import Tabulation as Tabulation

__all__ = ['from_file', 'HST']

def from_file(filespec: str | Path | FCPath, **parameters: Any) -> Snapshot: ...

class HST:
    def filespec(self, hdulist: HDUList) -> str: ...
    def telescope_name(self, hdulist: HDUList) -> str: ...
    def instrument_name(self, hdulist: HDUList) -> str: ...
    def detector_name(self, hdulist: HDUList, **parameters: Any) -> str: ...
    def data_array(self, hdulist: HDUList, **parameters: Any) -> ndarray: ...
    def error_array(self, hdulist: HDUList, **parameters: Any) -> ndarray: ...
    def quality_mask(self, hdulist: HDUList, **parameters: Any) -> ndarray: ...
    def time_limits(self, hdulist: HDUList, **parameters: Any) -> tuple[float, float]: ...
    def pos_targ(self, hdulist: HDUList, **parameters: Any) -> tuple[float, float]: ...
    def register_frame(self, hdulist: HDUList, fov: FOV, suffix: str = '',
        **parameters: Any) -> str | Frame | None: ...
    def register_tracker_frame(self, hdulist: HDUList, fov: FOV, suffix: str = '',
        **parameters: Any) -> str | None: ...
    def register_postarg_frame(self, hdulist: HDUList, fov: FOV, suffix: str = '',
        **parameters: Any) -> str | Frame: ...
    def dn_per_sec_factor(self, hdulist: HDUList) -> float: ...
    def iof_calibration(self, hdulist: HDUList, fov: FOV, extended: bool = True,
        **parameters: Any) -> Calibration | None: ...
    def target_body(self, hdulist: HDUList, **parameters: Any) -> Body | None: ...
    def get_headers(self, hdulist: HDUList, **parameters: Any) -> list[Header]: ...
    def construct_snapshot(self, hdulist: HDUList, **parameters: Any) -> Snapshot: ...
    def set_idc_path(self, idc_path: str) -> None: ...
    def idc_filespec(self, hdulist: HDUList) -> str: ...
    def load_idc_dict(self, hdulist: HDUList,
        keys: tuple[str, ...]) -> dict[tuple, dict[str, Any]]: ...
    def construct_idc_fov(self, fov_dict: dict[str, Any],
        platescale: float = 1.0) -> PolynomialFOV: ...
    def construct_drz_fov(self, fov_dict: dict[str, Any], hdulist: HDUList,
        platescale: float = 1.0) -> FlatFOV: ...
    def construct_fov(self, fov_dict: dict[str, Any], hdulist: HDUList,
        platescale: float = 1.0) -> FOV: ...
    def set_syn_path(self, syn_path: str) -> None: ...
    def get_syn_path(self) -> str: ...
    def load_syn_throughput(self, hdulist: HDUList, **parameters: Any) -> Tabulation: ...
    def solar_f(self, hdulist: HDUList, sun_range: float = 1.0, model: str = 'STIS',
        **parameters: Any) -> float: ...
    def bandpass(self, hdulist: HDUList, model: str = 'STIS',
        **parameters: Any) -> Tabulation: ...
    def compare_pivot_mean(self, hdulist: HDUList) -> tuple[float, float]: ...
    def compare_bandwidth_rms(self, hdulist: HDUList) -> tuple[float, float]: ...
    @staticmethod
    def from_hdulist(hdulist: HDUList, **parameters: Any) -> Snapshot: ...

##########################################################################################
