##########################################################################################
# oops/hosts/hst/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops.hosts.hst`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. Only package stubs exist, so a name is annotated when it is
imported from the package that exports it and not when it is imported from the module
that defines it. The stub describes the shape of the API exactly: every public name, its
parameters, which of them are keyword-only, and which have defaults. Types are given
where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any
from oops import Calibration as Calibration, FOV as FOV
from oops.fov import FlatFOV as FlatFOV, PolynomialFOV as PolynomialFOV
from tabulation import Tabulation as Tabulation

__all__ = ['from_file', 'HST']

def from_file(filespec: Any, **parameters: Any) -> Any: ...

class HST:
    def filespec(self, hdulist: Any) -> Any: ...
    def telescope_name(self, hdulist: Any) -> Any: ...
    def instrument_name(self, hdulist: Any) -> Any: ...
    def detector_name(self, hdulist: Any, **parameters: Any) -> Any: ...
    def data_array(self, hdulist: Any, **parameters: Any) -> Any: ...
    def error_array(self, hdulist: Any, **parameters: Any) -> Any: ...
    def quality_mask(self, hdulist: Any, **parameters: Any) -> Any: ...
    def time_limits(self, hdulist: Any, **parameters: Any) -> Any: ...
    def pos_targ(self, hdulist: Any, **parameters: Any) -> Any: ...
    def register_frame(self, hdulist: Any, fov: Any, suffix: str = '',
        **parameters: Any) -> Any: ...
    def register_tracker_frame(self, hdulist: Any, fov: Any, suffix: str = '',
        **parameters: Any) -> Any: ...
    def register_postarg_frame(self, hdulist: Any, fov: Any, suffix: str = '',
        **parameters: Any) -> Any: ...
    def dn_per_sec_factor(self, hdulist: list) -> None: ...
    def iof_calibration(self, hdulist: list, fov: FOV, extended: bool = True,
        **parameters: Any) -> Calibration: ...
    def target_body(self, hdulist: Any, **parameters: Any) -> Any: ...
    def get_headers(self, hdulist: Any, **parameters: Any) -> Any: ...
    def construct_snapshot(self, hdulist: Any, **parameters: Any) -> Any: ...
    def set_idc_path(self, idc_path: Any) -> None: ...
    def idc_filespec(self, hdulist: Any) -> Any: ...
    def load_idc_dict(self, hdulist: list, keys: tuple[str] | tuple) -> dict: ...
    def construct_idc_fov(self, fov_dict: dict,
        platescale: float = 1.0) -> PolynomialFOV: ...
    def construct_drz_fov(self, fov_dict: dict, hdulist: list,
        platescale: float = 1.0) -> FlatFOV: ...
    def construct_fov(self, fov_dict: dict, hdulist: list,
        platescale: float = 1.0) -> Any: ...
    def set_syn_path(self, syn_path: Any) -> None: ...
    def get_syn_path(self) -> Any: ...
    def load_syn_throughput(self, hdulist: Any, **parameters: Any) -> Any: ...
    def solar_f(self, hdulist: list, sun_range: float = 1.0, model: str = 'STIS',
        **parameters: Any) -> float: ...
    def bandpass(self, hdulist: list, model: str = 'STIS',
        **parameters: Any) -> Tabulation: ...
    def compare_pivot_mean(self, hdulist: Any) -> Any: ...
    def compare_bandwidth_rms(self, hdulist: Any) -> Any: ...
    @staticmethod
    def from_hdulist(hdulist: Any, **parameters: Any) -> Any: ...

##########################################################################################
