##########################################################################################
# oops/hosts/hst/wfpc2.pyi
##########################################################################################
"""Type stub for :mod:`oops.hosts.hst.wfpc2`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. The stub describes the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

from . import HST as HST

def from_file(filespec: Any, **parameters: Any) -> Any: ...
IDC_DICT: Any
GENERAL_SYN_FILES: Any
FILTER_SYN_FILE_PARTS: Any

class WFPC2(HST):
    def detector_name(self, hdulist: Any, **parameters: Any) -> Any: ...
    def filter_name(self, hdulist: Any) -> Any: ...
    def data_array(self, hdulist: Any, **parameters: Any) -> Any: ...
    def error_array(self, hdulist: Any, **parameters: Any) -> None: ...
    def quality_mask(self, hdulist: Any, **parameters: Any) -> Any: ...
    def register_frame(self, hdulist: Any,  # type: ignore[override]
        fov: Any, **parameters: Any) -> Any: ...
    def define_fov(self, hdulist: Any, **parameters: Any) -> Any: ...
    def select_syn_files(self, hdulist: Any, **parameters: Any) -> Any: ...
    def dn_per_sec_factor(self, hdulist: Any) -> Any: ...
    def get_headers(self, hdulist: Any, **parameters: Any) -> Any: ...
    @staticmethod
    def from_hdulist(hdulist: Any, **parameters: Any) -> Any: ...

##########################################################################################
