##########################################################################################
# oops/hosts/hst/nicmos/__init__.py
##########################################################################################

import astropy.io.fits as pyfits

from .. import HST

from filecache import FCPath

__all__ = ['from_file', 'NICMOS']

##########################################################################################
# Standard class methods
##########################################################################################

def from_file(filespec, **parameters):
    """An Observation object based on a given data file generated by HST/NICMOS.

    Parameters:
        filespec (str | pathlib.Path | FCPath): The path to the HST/NICMOS FITS file.
        **parameters (Any): The options recognized by :func:`~oops.hosts.hst.from_file`.

    Returns:
        Snapshot: The observation.

    Raises:
        IOError: If the file was not generated by HST/NICMOS.
    """

    filespec = FCPath(filespec)

    # Open the file
    local_path = filespec.retrieve()
    hdulist = pyfits.open(local_path)

    # Make an instance of the NICMOS class
    this = NICMOS()

    # Confirm that the telescope is HST
    if this.telescope_name(hdulist) != 'HST':
        raise IOError(f'not an HST file: {filespec}')

    # Confirm that the instrument is NICMOS
    if this.instrument_name(hdulist) != 'NICMOS':
        raise IOError(f'not an HST/NICMOS file: {filespec}')

    return NICMOS.from_hdulist(hdulist, **parameters)

##########################################################################################
# NICMOS class
##########################################################################################

# For each NICMOS detector, IDC_DICT returns a sub-dictionary of IDC parameters
# keyed by (FILTER,).
IDC_DICT = {'NIC1':None, 'NIC2': None, 'NIC3': None}

# These SYN file names apply to every NICMOS detector
NICMOS_SYN_FILES = ['OTA/hst_ota_???_syn.fits',
                    'NICMOS/nic_bend1_???_syn.fits',
                    'NICMOS/nic_primary_???_syn.fits',
                    'NICMOS/nic_pupil_???_syn.fits',
                    'NICMOS/nic_reimag_???_syn.fits',
                    'NICMOS/nic_secondary_???_syn.fits']


class NICMOS(HST):
    """The functions and properties unique to the NICMOS instrument.

    Everything else is inherited from higher levels in the class hierarchy.

    Objects of this class are empty; they only exist to support inheritance.
    """

    # The detector name for NICMOS must be extracted from the aperture
    def detector_name(self, hdulist):
        """The name of the HST detector used to obtain this file.

        Parameters:
            hdulist (astropy.io.fits.HDUList): The opened FITS file.

        Returns:
            str: "NIC1", "NIC2" or "NIC3", taken from the APERTURE keyword.
        """

        return hdulist[0].header['APERTURE'][0:4]

    # All NICMOS detectors have a single filter wheel. The name is identified by
    # FITS parameter FILTER.
    def filter_name(self, hdulist):
        """The name of the filter for this particular NICMOS detector.

        Parameters:
            hdulist (astropy.io.fits.HDUList): The opened FITS file.

        Returns:
            str: The value of the FILTER keyword in the primary header.
        """

        return hdulist[0].header['FILTER']

    # The IDC dictionaries for NICMOS detectors are all keyed by (FILTER,).
    def define_fov(self, hdulist, **parameters):
        """An FOV object defining the field of view of the given image file.

        Parameters:
            hdulist (astropy.io.fits.HDUList): The opened FITS file.
            **parameters (Any): Additional parameters; ignored.

        Returns:
            FOV: The field of view, as constructed by
            :meth:`~oops.hosts.hst.HST.construct_fov`.
        """

        global IDC_DICT

        # Identify the detector
        det = self.detector_name(hdulist)

        # Load the dictionary of IDC parameters if necessary
        if IDC_DICT[det] is None:
            IDC_DICT[det] = self.load_idc_dict(hdulist, ('FILTER',))

        # Define the key into the dictionary
        idc_key = (hdulist[0].header['FILTER'],)

        return self.construct_fov(IDC_DICT[det][idc_key], hdulist)

    def select_syn_files(self, hdulist, **parameters):
        """The SYN files defining the throughput of this filter combination.

        The profiles in these files are multiplied together to obtain the throughput of
        the given instrument, detector and filter combination.

        Parameters:
            hdulist (astropy.io.fits.HDUList): The opened FITS file.
            **parameters (Any): Additional parameters; ignored.

        Returns:
            list[str]: The paths of the SYN files relative to the SYN root directory,
            each containing a glob pattern in place of the version number.
        """

        global NICMOS_SYN_FILES

        # Copy all the NICMOS general file names
        syn_filenames = []
        for filename in NICMOS_SYN_FILES:
            syn_filenames.append(filename)

        # Append all the detector-specific file names
        for filename in self.DETECTOR_SYN_FILES:
            syn_filenames.append(filename)

        # Add the filter file name
        syn_filenames.append(self.FILTER_SYN_FILE_PARTS[0] +
                             hdulist[0].header['FILTER'].lower() +
                             self.FILTER_SYN_FILE_PARTS[1])

        return syn_filenames

    def dn_per_sec_factor(self, hdulist):
        """The factor that converts a pixel value to DN per second.

        Parameters:
            hdulist (astropy.io.fits.HDUList): The opened FITS file.

        Returns:
            float: The factor to multiply a pixel value by to get DN/sec.
        """

        return 1.

    @staticmethod
    def from_hdulist(hdulist, **parameters):
        """An Observation object based on an HST data file generated by HST/NICMOS.

        Parameters:
            hdulist (astropy.io.fits.HDUList): The opened FITS file.
            **parameters (Any): The options recognized by
                :func:`~oops.hosts.hst.from_file`.

        Returns:
            Snapshot: The observation.

        Raises:
            IOError: If the detector is not NIC1, NIC2 or NIC3.
        """

        # Make an instance of the NICMOS class
        this = NICMOS()

        # Figure out the detector
        detector = this.detector_name(hdulist)

        if detector == 'NIC1':
            from .nic1 import NIC1
            obs = NIC1.from_hdulist( hdulist, **parameters)

        elif detector == 'NIC2':
            from .nic2 import NIC2
            obs = NIC2.from_hdulist(hdulist, **parameters)

        elif detector == 'NIC3':
            from .nic3 import NIC3
            obs = NIC3.from_hdulist(hdulist, **parameters)

        else:
            raise IOError('unrecognized detector in HST/NICMOS file ' +
                          this.filespec(hdulist) + ': ' + detector)

        return obs

##########################################################################################
