##########################################################################################
# oops/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. Only package stubs exist, so a name is annotated when it is
imported from the package that exports it and not when it is imported from the module
that defines it. The stub describes the shape of the API exactly: every public name, its
parameters, which of them are keyword-only, and which have defaults. Types are given
where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any
from numpy import ndarray, number
from polymath import (Boolean, Matrix, Matrix3, Pair, Quaternion, Qube, Scalar, Vector,
                      Vector3)
import oops.backplane as backplane
import oops.body as body
import oops.cadence as cadence
import oops.calibration as calibration
import oops.config as config
import oops.constants as constants
import oops.event as event
import oops.fittable as fittable
import oops.fov as fov
import oops.frame as frame
import oops.gravity as gravity
import oops.meshgrid as meshgrid
import oops.mutable as mutable
import oops.observation as obs
import oops.observation as observation
import oops.path as path
import oops.spice_support as spice
import oops.surface as surface
import oops.transform as transform
from oops.backplane import Backplane as Backplane
from oops.cadence import Cadence as Cadence
from oops.calibration import Calibration as Calibration
from oops.fov import FOV as FOV
from oops.frame import Frame as Frame
from oops.gravity import Gravity as Gravity
from oops.observation import Observation as Observation
from oops.oops import Oops as Oops
from oops.path import Path as Path
from oops.surface import Surface as Surface

# Parameters documented as a polymath type are passed through `as_scalar` and its
# siblings, so each accepts the class, a number, or a nested sequence of numbers.
# `str` is excluded deliberately: no polymath constructor accepts one.
_Numeric = float | number | list['_Numeric'] | tuple['_Numeric', ...]
Matrix3Like = Matrix3 | ndarray | _Numeric
PairLike = Pair | ndarray | _Numeric
ScalarLike = Scalar | ndarray | _Numeric
Vector3Like = Vector3 | ndarray | _Numeric

BooleanLike = Boolean | bool | ndarray | _Numeric
VectorLike = Vector | ndarray | _Numeric

__all__ = ['cadence', 'calibration', 'fov', 'gravity', 'frame', 'observation', 'path',
           'surface', 'obs', 'backplane', 'body', 'event', 'fittable', 'meshgrid',
           'transform', 'Cadence', 'Calibration', 'FOV', 'Gravity', 'Frame',
           'Observation', 'Path', 'Surface', 'Backplane', 'Body', 'Event', 'Fittable',
           'Meshgrid', 'Transform', 'constants', 'spice', 'config', 'mutable', 'C',
           'C_INVERSE', 'RPD', 'DPR', 'SPR', 'RPS', 'SPD', 'AU', 'PI', 'TWOPI', 'HALFPI',
           'Boolean', 'Matrix', 'Matrix3', 'Pair', 'Quaternion', 'Qube', 'Scalar',
           'Vector', 'Vector3']

class Body(Oops):
    BODY_REGISTRY: Any
    STANDARD_BODIES: Any
    name: Any
    is_standard: bool
    spk: Any
    spice_name: Any
    spice_id: Any
    path: Any
    frame: Any
    ring_frame: Any
    ring_epoch: Any
    ring_is_retrograde: bool
    ring_pole: Any
    ring_body: Any
    is_ring: bool
    invariable_pole: Any
    invariable_frame: Any
    parent: Any
    barycenter: Any
    surface: Any
    radius: float
    inner_radius: float
    gravity: Any
    lightsource: Any
    keywords: Any
    child_names: Any
    is_registered: bool
    def __init__(self, name: Any, path: Any, frame: Any, parent: Any = None,
        barycenter: Any = None, spice_name: Any = None) -> None: ...
    def apply_surface(self, surface: Any, radius: Any,
        inner_radius: float = 0.0) -> None: ...
    def apply_ring_frame(self, epoch: Any = None, retrograde: bool = False,
        pole: Any = None) -> None: ...
    def apply_gravity(self, gravity: Any) -> None: ...
    def add_keywords(self, keywords: Any) -> None: ...
    @property
    def children(self) -> Any: ...
    def select_children(self, include_all: Any = None, include_any: Any = None,
        exclude: Any = None, radius: Any = None, recursive: bool = False) -> Any: ...
    @staticmethod
    def name_in(bodies: Any, names: Any) -> Any: ...
    @staticmethod
    def name_not_in(bodies: Any, names: Any) -> Any: ...
    @staticmethod
    def radius_in_range(bodies: Any, min: Any, max: Any = ...) -> Any: ...
    @staticmethod
    def radius_not_in_range(bodies: Any, min: Any, max: Any = ...) -> Any: ...
    @staticmethod
    def surface_class_in(bodies: Any, class_names: Any) -> Any: ...
    @staticmethod
    def surface_class_not_in(bodies: Any, class_names: Any) -> Any: ...
    @staticmethod
    def has_gravity(bodies: Any) -> Any: ...
    @staticmethod
    def has_no_gravity(bodies: Any) -> Any: ...
    @staticmethod
    def has_children(bodies: Any) -> Any: ...
    @staticmethod
    def has_no_children(bodies: Any) -> Any: ...
    @staticmethod
    def has_ring(bodies: Any) -> Any: ...
    @staticmethod
    def has_no_ring(bodies: Any) -> Any: ...
    @staticmethod
    def keywords_include_any(bodies: Any, keywords: Any) -> Any: ...
    @staticmethod
    def keywords_include_all(bodies: Any, keywords: Any) -> Any: ...
    @staticmethod
    def keywords_do_not_include(bodies: Any, keywords: Any) -> Any: ...
    @staticmethod
    def define_multipath(bodies: Any, origin: str = 'SSB', frame: str = 'J2000',
        path_id: Any = None) -> Any: ...
    @staticmethod
    def lookup(key: Any) -> Any: ...
    @staticmethod
    def exists(key: Any) -> Any: ...
    @staticmethod
    def as_body(body: Any) -> Any: ...
    @staticmethod
    def as_body_name(body: Any) -> Any: ...
    @staticmethod
    def reset_registry() -> None: ...
    def as_path(self) -> Any: ...
    def photon_to_event(self, event: Event, derivs: bool = False,
        guess: ScalarLike | None = None, antimask: ndarray | bool | None = None,
        quick: dict | bool | None = None,
        converge: dict | None = None) -> tuple[Event, Event]: ...
    @staticmethod
    def define_solar_system(start_time: str | None = None, stop_time: str | None = None,
        asof: str | None = None, **args: Any) -> list: ...
    MARS_MOONS_LOADED: Any
    JUPITER_MOONS_LOADED: Any
    SATURN_MOONS_LOADED: Any
    URANUS_MOONS_LOADED: Any
    NEPTUNE_MOONS_LOADED: Any
    PLUTO_MOONS_LOADED: Any
    @staticmethod
    def define_bodies(spice_ids: Any, parent: Any, barycenter: Any, keywords: Any,
        is_standard: bool = False) -> None: ...
    @staticmethod
    def define_body(spice_id: Any, parent: Any, barycenter: Any, keywords: Any,
        is_standard: bool = False, name: Any = None) -> None: ...
    @staticmethod
    def define_ring(parent_name: str, ring_name: str, radii: tuple | float | None,
        keywords: list, retrograde: bool = False, barycenter_name: str | None = None,
        pole: Vector3Like | None = None, is_standard: bool = False) -> Any: ...
    @staticmethod
    def define_orbit(parent_name: Any, ring_name: Any, elements: Any, epoch: Any,
        reference: Any, keywords: Any, is_standard: bool = False) -> None: ...
    @staticmethod
    def define_small_body(spice_id: Any, name: Any = None, spk: Any = None,
        keywords: Any = None, parent: str = 'SUN', barycenter: str = 'SSB',
        is_standard: bool = False) -> None: ...

class Event(Oops):
    SSB: Any
    ARR_VEC3_PROPERTIES: Any
    DEP_VEC3_PROPERTIES: Any
    SPECIAL_PROPERTIES: Any
    def __init__(self, time: ScalarLike, state: Vector3Like, origin: Path | str,
        frame: Frame | None = None, **more: Any) -> None: ...
    @property
    def time(self) -> Any: ...
    @property
    def state(self) -> Any: ...
    @property
    def pos(self) -> Any: ...
    @property
    def vel(self) -> Any: ...
    @property
    def origin(self) -> Any: ...
    @property
    def origin_id(self) -> Any: ...
    @property
    def frame(self) -> Any: ...
    @property
    def frame_id(self) -> Any: ...
    @property
    def subfields(self) -> Any: ...
    @property
    def shape(self) -> Any: ...
    @property
    def size(self) -> Any: ...
    @property
    def mask(self) -> Any: ...
    @property
    def antimask(self) -> Any: ...
    @property
    def ssb(self) -> Any: ...
    @property
    def xform_to_j2000(self) -> Any: ...
    @property
    def wod(self) -> Any: ...
    def empty_cache(self) -> None: ...
    def has_arrivals(self) -> Any: ...
    def has_departures(self) -> Any: ...
    @property
    def arr(self) -> Any: ...
    @arr.setter
    def arr(self, value: Any) -> None: ...
    @property
    def arr_ap(self) -> Any: ...
    @arr_ap.setter
    def arr_ap(self, value: Any) -> None: ...
    @property
    def arr_j2000(self) -> Any: ...
    @arr_j2000.setter
    def arr_j2000(self, value: Any) -> None: ...
    @property
    def arr_ap_j2000(self) -> Any: ...
    @arr_ap_j2000.setter
    def arr_ap_j2000(self, value: Any) -> None: ...
    @property
    def arr_lt(self) -> Any: ...
    @arr_lt.setter
    def arr_lt(self, value: Any) -> None: ...
    @property
    def neg_arr(self) -> Any: ...
    @neg_arr.setter
    def neg_arr(self, value: Any) -> None: ...
    @property
    def neg_arr_ap(self) -> Any: ...
    @neg_arr_ap.setter
    def neg_arr_ap(self, value: Any) -> None: ...
    @property
    def neg_arr_j2000(self) -> Any: ...
    @neg_arr_j2000.setter
    def neg_arr_j2000(self, value: Any) -> None: ...
    @property
    def neg_arr_ap_j2000(self) -> Any: ...
    @neg_arr_ap_j2000.setter
    def neg_arr_ap_j2000(self, value: Any) -> None: ...
    @property
    def dep(self) -> Any: ...
    @dep.setter
    def dep(self, value: Any) -> None: ...
    @property
    def dep_ap(self) -> Any: ...
    @dep_ap.setter
    def dep_ap(self, value: Any) -> None: ...
    @property
    def dep_j2000(self) -> Any: ...
    @dep_j2000.setter
    def dep_j2000(self, value: Any) -> None: ...
    @property
    def dep_ap_j2000(self) -> Any: ...
    @dep_ap_j2000.setter
    def dep_ap_j2000(self, value: Any) -> None: ...
    @property
    def dep_lt(self) -> Any: ...
    @dep_lt.setter
    def dep_lt(self, value: Any) -> None: ...
    @property
    def perp(self) -> Any: ...
    @perp.setter
    def perp(self, value: Any) -> None: ...
    @property
    def vflat(self) -> Vector3: ...
    @vflat.setter
    def vflat(self, value: Any) -> None: ...
    def insert_subfield(self, name: Any, value: Any) -> None: ...
    def get_subfield(self, name: Any) -> Any: ...
    def copy(self, omit: list | tuple = ()) -> Any: ...
    def without_derivs(self) -> Any: ...
    def as_all_masked(self, origin: Path | str | None = None,
        frame: Frame | str | None = None, *, broadcast: tuple | None = None) -> Any: ...
    def mask_where(self, mask: Any) -> Any: ...
    def remask(self, mask: Any) -> Any: ...
    def replace(self, *args: Any) -> Any: ...
    def with_time_derivs(self) -> Any: ...
    def with_los_derivs(self) -> Any: ...
    def with_pos_derivs(self) -> Event: ...
    def with_lt_derivs(self) -> Event: ...
    def with_dep_derivs(self) -> Event: ...
    def with_dlt_derivs(self) -> Event: ...
    def shrink(self, antimask: BooleanLike | bool | None) -> Event: ...
    def unshrink(self, antimask: BooleanLike | bool | None, *,
        shape: tuple | None = None) -> Event: ...
    def wrt_ssb(self, *, derivs: bool = True, quick: dict | None = None) -> Any: ...
    def from_ssb(self, path: Path, frame: Frame, *, derivs: bool = True,
        quick: dict | None = None) -> Any: ...
    def wrt(self, path: Path | str | None = None, frame: Frame | str | None = None, *,
        derivs: bool = True, quick: dict | None = None,
        include_xform: bool = False) -> Event | tuple[Event, Transform]: ...
    def wrt_path(self, path: Path, *, derivs: bool = True,
        quick: dict | None = None) -> Any: ...
    def wrt_frame(self, frame: Frame, *, derivs: bool = True, quick: dict | None = None,
        include_xform: bool = False) -> Any: ...
    def rotate_by_frame(self, frame: Frame, *, derivs: bool = True,
        quick: dict | None = None, include_xform: bool = False) -> Any: ...
    def unrotate_by_frame(self, frame: Frame, *, derivs: bool = True,
        quick: dict | None = None) -> Any: ...
    def collapse_time(self, threshold: float | None = None) -> Any: ...
    def sub(self, reference: Event, *, quick: dict | bool | None = None) -> Event: ...
    def apparent_ray_ssb(self, ray_ssb: Vector3Like, *, derivs: bool = False,
        quick: dict | None = None) -> Any: ...
    def actual_ray_ssb(self, ray_ap_ssb: Vector3Like, *, derivs: bool = False,
        quick: dict | None = None) -> Any: ...
    def apparent_arr(self, *, derivs: bool = False, quick: dict | None = None) -> Any: ...
    def actual_arr(self, *, derivs: bool = False, quick: dict | None = None) -> Any: ...
    def apparent_dep(self, *, derivs: bool = False, quick: dict | None = None) -> Any: ...
    def actual_dep(self, *, derivs: bool = False, quick: dict | None = None) -> Any: ...
    def incidence_angle(self, apparent: bool = False, *, derivs: bool = False,
        quick: dict | None = None) -> Any: ...
    def emission_angle(self, apparent: bool = False, *, derivs: bool = False,
        quick: dict | None = None) -> Any: ...
    def phase_angle(self, apparent: bool = False, *, derivs: bool = False,
        quick: dict | None = None) -> Any: ...
    def ra_and_dec(self, apparent: bool = False, *, derivs: bool = False,
        subfield: str = 'arr', quick: dict | None = None,
        frame: Frame | str | None = 'J2000') -> Any: ...

class Fittable(Oops):
    @property
    def is_frozen(self) -> bool: ...
    @property
    def version(self) -> int: ...
    def set_params(self, params: Any) -> bool: ...
    def refresh(self) -> bool: ...
    def copy(self) -> Fittable: ...
    def freeze(self) -> bool: ...

class Meshgrid(Oops):
    fov: Any
    uv: Any
    uv_w_duv_duv: Any
    shape: Any
    center_uv: Any
    center_uv_w_duv_duv: Any
    def __init__(self, fov: FOV, uv_pair: PairLike, center_uv: PairLike | None = None, *,
        fov_kwargs: dict | None = None) -> None: ...
    @staticmethod
    def for_fov(fov: FOV, origin: PairLike | None = None, undersample: PairLike = 1,
        oversample: PairLike = 1, limit: PairLike | None = None, swap: bool = False,
        fov_kwargs: dict | None = None) -> Meshgrid: ...
    @staticmethod
    def for_fov_center(fov: FOV, origin: PairLike | None = None,
        fov_kwargs: dict | None = None) -> Meshgrid: ...
    @staticmethod
    def for_shape(fov: FOV, shape: tuple, u_axis: int = -1, v_axis: int = -1,
        origin: PairLike | None = None, undersample: PairLike = 1,
        oversample: PairLike = 1, limit: PairLike | None = None,
        center_uv: PairLike | tuple[float, float] | tuple | None = None,
        fov_kwargs: dict | None = None) -> Meshgrid: ...
    def los_w_derivs(self, time: ScalarLike | None = None) -> Vector3: ...
    def los(self, time: ScalarLike | None = None) -> Vector3: ...
    def dlos_duv(self, time: ScalarLike | None = None) -> Vector3: ...
    def uv_w_derivs(self, time: ScalarLike | None = None) -> Pair: ...
    def duv_dlos(self, time: ScalarLike | None = None) -> Pair: ...
    def center_los_w_derivs(self, time: ScalarLike | None = None) -> Vector3: ...
    def center_los(self, time: ScalarLike | None = None) -> Vector3: ...
    def center_dlos_duv(self, time: ScalarLike | None = None) -> Vector3: ...
    def center_uv_w_derivs(self, time: ScalarLike | None = None) -> Pair: ...
    def center_duv_dlos(self, time: ScalarLike | None = None) -> Pair: ...

class Transform(Oops):
    matrix: Any
    omega: Any
    is_fixed: Any
    frame: Any
    reference: Any
    origin: Any
    def __init__(self, matrix: Matrix3Like, omega: Vector3Like, frame: Frame | str,
        reference: Frame | str, *, origin: Path | str | None = None) -> None: ...
    @property
    def shape(self) -> Any: ...
    @property
    def omega1(self) -> Any: ...
    @property
    def matrix_with_deriv(self) -> Any: ...
    @property
    def inverse_matrix(self) -> Any: ...
    @property
    def inverse_with_deriv(self) -> Any: ...
    @property
    def wod(self) -> Any: ...
    @staticmethod
    def identity(frame: Frame | str) -> Transform: ...
    def rotate(self, pos: Vector3Like | VectorLike | Matrix,
        derivs: bool = True) -> Vector3: ...
    def rotate_pos_vel(self, pos: Vector3Like,
        vel: Vector3Like) -> tuple[Vector3, Vector3]: ...
    def unrotate(self, pos: Vector3Like | VectorLike | Matrix,
        derivs: bool = True) -> Vector3: ...
    def unrotate_pos_vel(self, pos: Vector3Like,
        vel: Vector3Like) -> tuple[Vector3, Vector3]: ...
    def invert(self) -> Transform: ...
    def rotate_transform(self, arg: Transform) -> Transform: ...
    def unrotate_transform(self, arg: Transform) -> Transform: ...
    IDENTITY: Any

C: float

C_INVERSE: float

RPD: float

DPR: float

SPR: float

RPS: float

SPD: float

AU: float

PI: float

TWOPI: float

HALFPI: float

##########################################################################################
