##########################################################################################
# oops/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops`.

The source types its methods in their docstrings rather than in their signatures, so the
type information for public symbols is published here instead. Only package stubs exist,
so a name is annotated when it is imported from the package that exports it and not when
it is imported from the module that defines it. The stub describes the shape of the API
exactly: every public name, its parameters, which of them are keyword-only, and which have
defaults. Types are given where they are unambiguous and are `Any` elsewhere.
"""

from collections.abc import Iterable
from typing import Any
from numpy import ndarray
from polymath import (Boolean, Matrix, Matrix3, Pair, Quaternion, Qube, Scalar, Vector,
                      Vector3)
# Parameters documented as a polymath type are passed through `as_scalar` and its
# siblings, so each accepts the class, a number, or a nested sequence of numbers.
# `polymath.typedefs` names each of those unions.
from polymath.typedefs import (BooleanLike, MaskType, Matrix3Like, MatrixLike, PairLike,
                               ScalarLike, Vector3Like, VectorLike)
import oops.backplane as backplane
import oops.body as body
import oops.cadence as cadence
import oops.calibration as calibration
import oops.config as config
import oops.constants as constants
import oops.event as event
import oops.fittable as fittable
import oops.fov as fov
import oops.frame as frame
import oops.gravity as gravity
import oops.meshgrid as meshgrid
import oops.mutable as mutable
import oops.observation as obs
import oops.observation as observation
import oops.path as path
import oops.spice_support as spice
import oops.surface as surface
import oops.transform as transform
from oops.backplane import Backplane as Backplane
from oops.cadence import Cadence as Cadence
from oops.calibration import Calibration as Calibration
from oops.fov import FOV as FOV
from oops.frame import Frame as Frame
from oops.gravity import Gravity as Gravity
from oops.lightsource import LightSource
from oops.observation import Observation as Observation
from oops.oops import Oops as Oops
from oops.path import MultiPath
from oops.path import Path as Path
from oops.surface import Surface as Surface

__all__ = ['cadence', 'calibration', 'fov', 'gravity', 'frame', 'observation', 'path',
           'surface', 'obs', 'backplane', 'body', 'event', 'fittable', 'meshgrid',
           'transform', 'Cadence', 'Calibration', 'FOV', 'Gravity', 'Frame',
           'Observation', 'Path', 'Surface', 'Backplane', 'Body', 'Event', 'Fittable',
           'Meshgrid', 'Transform', 'constants', 'spice', 'config', 'mutable', 'C',
           'C_INVERSE', 'RPD', 'DPR', 'SPR', 'RPS', 'SPD', 'AU', 'PI', 'TWOPI', 'HALFPI',
           'Boolean', 'Matrix', 'Matrix3', 'Pair', 'Quaternion', 'Qube', 'Scalar',
           'Vector', 'Vector3', 'OopsException', 'OopsIndexError', 'OopsKeyError',
           'OopsRuntimeError', 'OopsTypeError', 'OopsValueError']

class OopsException(Exception): ...
class OopsIndexError(IndexError, OopsException): ...
class OopsKeyError(KeyError, OopsException): ...
class OopsRuntimeError(RuntimeError, OopsException): ...
class OopsTypeError(TypeError, OopsException): ...
class OopsValueError(ValueError, OopsException): ...

class Body(Oops):
    BODY_REGISTRY: dict[str, Body]
    STANDARD_BODIES: set[str]
    name: str
    is_standard: bool
    spk: str | None
    spice_name: str
    spice_id: int | None
    path: Path
    frame: Frame
    ring_frame: Frame | None
    ring_epoch: float | None
    ring_is_retrograde: bool
    ring_pole: Vector3 | None
    ring_body: Body | None
    is_ring: bool
    invariable_pole: Vector3 | None
    invariable_frame: Frame | None
    parent: Body | None
    barycenter: Body | None
    surface: Surface | None
    radius: float
    inner_radius: float
    gravity: Gravity | None
    lightsource: LightSource | None
    keywords: list[str]
    child_names: list[str]
    is_registered: bool
    def __init__(self, name: str, path: Path | str, frame: Frame | str,
        parent: Body | str | None = None, barycenter: Body | str | None = None,
        spice_name: str | None = None) -> None: ...
    def apply_surface(self, surface: Surface, radius: float,
        inner_radius: float = 0.0) -> None: ...
    def apply_ring_frame(self, epoch: float | None = None, retrograde: bool = False,
        pole: Vector3Like | None = None) -> None: ...
    def apply_gravity(self, gravity: Gravity | None) -> None: ...
    def add_keywords(self, keywords: str | list[str]) -> None: ...
    @property
    def children(self) -> list[Body]: ...
    def select_children(self, include_all: str | list[str] | None = None,
        include_any: str | list[str] | None = None,
        exclude: str | list[str] | None = None,
        radius: float | tuple[float, float] | None = None,
        recursive: bool = False) -> list[Body]: ...
    @staticmethod
    def name_in(bodies: list[Body], names: str | list[str]) -> list[Body]: ...
    @staticmethod
    def name_not_in(bodies: list[Body], names: str | list[str]) -> list[Body]: ...
    @staticmethod
    def radius_in_range(bodies: list[Body], min: float,
        max: float = ...) -> list[Body]: ...
    @staticmethod
    def radius_not_in_range(bodies: list[Body], min: float,
        max: float = ...) -> list[Body]: ...
    @staticmethod
    def surface_class_in(bodies: list[Body],
        class_names: str | list[str]) -> list[Body]: ...
    @staticmethod
    def surface_class_not_in(bodies: list[Body],
        class_names: str | list[str]) -> list[Body]: ...
    @staticmethod
    def has_gravity(bodies: list[Body]) -> list[Body]: ...
    @staticmethod
    def has_no_gravity(bodies: list[Body]) -> list[Body]: ...
    @staticmethod
    def has_children(bodies: list[Body]) -> list[Body]: ...
    @staticmethod
    def has_no_children(bodies: list[Body]) -> list[Body]: ...
    @staticmethod
    def has_ring(bodies: list[Body]) -> list[Body]: ...
    @staticmethod
    def has_no_ring(bodies: list[Body]) -> list[Body]: ...
    @staticmethod
    def keywords_include_any(bodies: list[Body],
        keywords: str | list[str]) -> list[Body]: ...
    @staticmethod
    def keywords_include_all(bodies: list[Body],
        keywords: str | list[str]) -> list[Body]: ...
    @staticmethod
    def keywords_do_not_include(bodies: list[Body],
        keywords: str | list[str]) -> list[Body]: ...
    @staticmethod
    def define_multipath(bodies: list[Body], origin: Path | str = 'SSB',
        frame: Frame | str = 'J2000', path_id: str | None = None) -> MultiPath: ...
    @staticmethod
    def lookup(key: str) -> Body: ...
    @staticmethod
    def exists(key: str) -> bool: ...
    @staticmethod
    def as_body(body: Body | str) -> Body: ...
    @staticmethod
    def as_body_name(body: Body | str) -> str: ...
    @staticmethod
    def reset_registry() -> None: ...
    def as_path(self) -> Path: ...
    def photon_to_event(self, event: Event, derivs: bool = False,
        guess: ScalarLike | None = None, antimask: ndarray | bool | None = None,
        quick: dict | bool | None = None,
        converge: dict | None = None) -> tuple[Event, Event]: ...
    @staticmethod
    def define_solar_system(start_time: str | float | None = None,
        stop_time: str | float | None = None, asof: str | None = None,
        **args: Any) -> list[str]: ...
    MARS_MOONS_LOADED: list[int]
    JUPITER_MOONS_LOADED: list[int]
    SATURN_MOONS_LOADED: list[int]
    URANUS_MOONS_LOADED: list[int]
    NEPTUNE_MOONS_LOADED: list[int]
    PLUTO_MOONS_LOADED: list[int]
    @staticmethod
    def define_bodies(spice_ids: list[int | str], parent: Body | str | None,
        barycenter: Body | str | None, keywords: list[str],
        is_standard: bool = False) -> None: ...
    @staticmethod
    def define_body(spice_id: int | str, parent: Body | str | None,
        barycenter: Body | str | None, keywords: list[str], is_standard: bool = False,
        name: str | None = None) -> None: ...
    @staticmethod
    def define_ring(parent_name: str, ring_name: str, radii: tuple | float | None,
        keywords: list, retrograde: bool = False, barycenter_name: str | None = None,
        pole: Vector3Like | None = None, is_standard: bool = False) -> Body: ...
    @staticmethod
    def define_orbit(parent_name: str, ring_name: str, elements: tuple[float, ...],
        epoch: float, reference: Frame | str, keywords: list[str],
        is_standard: bool = False) -> None: ...
    @staticmethod
    def define_small_body(spice_id: int | str, name: str | None = None,
        spk: str | None = None, keywords: list[str] | None = None, parent: str = 'SUN',
        barycenter: str = 'SSB', is_standard: bool = False) -> None: ...

class Event(Oops):
    SSB: Event
    def __init__(self, time: ScalarLike, state: Vector3Like, origin: Path | str,
        frame: Frame | str | None = None, **more: Any) -> None: ...
    @property
    def time(self) -> Scalar: ...
    @property
    def state(self) -> Vector3: ...
    @property
    def pos(self) -> Vector3: ...
    @property
    def vel(self) -> Vector3: ...
    @property
    def origin(self) -> Path: ...
    @property
    def origin_id(self) -> str: ...
    @property
    def frame(self) -> Frame: ...
    @property
    def frame_id(self) -> str: ...
    @property
    def subfields(self) -> dict[str, Any]: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def size(self) -> int: ...
    @property
    def mask(self) -> MaskType: ...
    @property
    def antimask(self) -> MaskType: ...
    @property
    def ssb(self) -> Event: ...
    @property
    def xform_to_j2000(self) -> Transform: ...
    @property
    def wod(self) -> Event: ...
    def empty_cache(self) -> None: ...
    def has_arrivals(self) -> bool: ...
    def has_departures(self) -> bool: ...
    @property
    def arr(self) -> Vector3 | None: ...
    @arr.setter
    def arr(self, value: Vector3Like) -> None: ...
    @property
    def arr_ap(self) -> Vector3 | None: ...
    @arr_ap.setter
    def arr_ap(self, value: Vector3Like) -> None: ...
    @property
    def arr_j2000(self) -> Vector3 | None: ...
    @arr_j2000.setter
    def arr_j2000(self, value: Vector3Like) -> None: ...
    @property
    def arr_ap_j2000(self) -> Vector3 | None: ...
    @arr_ap_j2000.setter
    def arr_ap_j2000(self, value: Vector3Like) -> None: ...
    @property
    def arr_lt(self) -> Scalar | None: ...
    @arr_lt.setter
    def arr_lt(self, value: ScalarLike) -> None: ...
    @property
    def neg_arr(self) -> Vector3 | None: ...
    @neg_arr.setter
    def neg_arr(self, value: Vector3Like) -> None: ...
    @property
    def neg_arr_ap(self) -> Vector3 | None: ...
    @neg_arr_ap.setter
    def neg_arr_ap(self, value: Vector3Like) -> None: ...
    @property
    def neg_arr_j2000(self) -> Vector3 | None: ...
    @neg_arr_j2000.setter
    def neg_arr_j2000(self, value: Vector3Like) -> None: ...
    @property
    def neg_arr_ap_j2000(self) -> Vector3 | None: ...
    @neg_arr_ap_j2000.setter
    def neg_arr_ap_j2000(self, value: Vector3Like) -> None: ...
    @property
    def dep(self) -> Vector3 | None: ...
    @dep.setter
    def dep(self, value: Vector3Like) -> None: ...
    @property
    def dep_ap(self) -> Vector3 | None: ...
    @dep_ap.setter
    def dep_ap(self, value: Vector3Like) -> None: ...
    @property
    def dep_j2000(self) -> Vector3 | None: ...
    @dep_j2000.setter
    def dep_j2000(self, value: Vector3Like) -> None: ...
    @property
    def dep_ap_j2000(self) -> Vector3 | None: ...
    @dep_ap_j2000.setter
    def dep_ap_j2000(self, value: Vector3Like) -> None: ...
    @property
    def dep_lt(self) -> Scalar | None: ...
    @dep_lt.setter
    def dep_lt(self, value: ScalarLike) -> None: ...
    @property
    def perp(self) -> Vector3 | None: ...
    @perp.setter
    def perp(self, value: Vector3Like) -> None: ...
    @property
    def vflat(self) -> Vector3: ...
    @vflat.setter
    def vflat(self, value: Vector3Like) -> None: ...
    def insert_subfield(self, name: str, value: Any) -> None: ...
    def get_subfield(self, name: str) -> Any: ...
    def copy(self, omit: str | list[str] | tuple[str, ...] = ()) -> Event: ...
    def without_derivs(self) -> Event: ...
    def as_all_masked(self, origin: Path | str | None = None,
        frame: Frame | str | None = None, *,
        broadcast: tuple[int, ...] | None = None) -> Event: ...
    def mask_where(self, mask: MaskType) -> Event: ...
    def remask(self, mask: MaskType) -> Event: ...
    def replace(self, *args: Any) -> Event: ...
    def with_time_derivs(self) -> Event: ...
    def with_los_derivs(self) -> Event: ...
    def with_pos_derivs(self) -> Event: ...
    def with_lt_derivs(self) -> Event: ...
    def with_dep_derivs(self) -> Event: ...
    def with_dlt_derivs(self) -> Event: ...
    def shrink(self, antimask: BooleanLike | None) -> Event: ...
    def unshrink(self, antimask: BooleanLike | None, *,
        shape: tuple[int, ...] | None = None) -> Event: ...
    def wrt_ssb(self, *, derivs: bool = True,
        quick: dict | bool | None = None) -> Event: ...
    def from_ssb(self, path: Path | str | None, frame: Frame | str | None, *,
        derivs: bool = True, quick: dict | bool | None = None) -> Event: ...
    def wrt(self, path: Path | str | None = None, frame: Frame | str | None = None, *,
        derivs: bool = True, quick: dict | bool | None = None,
        include_xform: bool = False) -> Event | tuple[Event, Transform]: ...
    def wrt_path(self, path: Path | str | None, *, derivs: bool = True,
        quick: dict | bool | None = None) -> Event: ...
    def wrt_frame(self, frame: Frame | str | None, *, derivs: bool = True,
        quick: dict | bool | None = None, include_xform: bool = False) -> Event: ...
    def rotate_by_frame(self, frame: Frame | str, *, derivs: bool = True,
        quick: dict | bool | None = None, include_xform: bool = False) -> Event: ...
    def unrotate_by_frame(self, frame: Frame | str, *, derivs: bool = True,
        quick: dict | bool | None = None) -> Event: ...
    def collapse_time(self, threshold: float | None = None) -> Event: ...
    def sub(self, reference: Event, *, quick: dict | bool | None = None) -> Event: ...
    def apparent_ray_ssb(self, ray_ssb: Vector3Like, *, derivs: bool = False,
        quick: dict | bool | None = None) -> Vector3: ...
    def actual_ray_ssb(self, ray_ap_ssb: Vector3Like, *, derivs: bool = False,
        quick: dict | bool | None = None) -> Vector3: ...
    def apparent_arr(self, *, derivs: bool = False,
        quick: dict | bool | None = None) -> Vector3: ...
    def actual_arr(self, *, derivs: bool = False,
        quick: dict | bool | None = None) -> Vector3: ...
    def apparent_dep(self, *, derivs: bool = False,
        quick: dict | None = None) -> Vector3: ...
    def actual_dep(self, *, derivs: bool = False,
        quick: dict | None = None) -> Vector3: ...
    def incidence_angle(self, apparent: bool = False, *, derivs: bool = False,
        quick: dict | None = None) -> Scalar: ...
    def emission_angle(self, apparent: bool = False, *, derivs: bool = False,
        quick: dict | None = None) -> Scalar: ...
    def phase_angle(self, apparent: bool = False, *, derivs: bool = False,
        quick: dict | None = None) -> Scalar: ...
    def ra_and_dec(self, apparent: bool = False, *, derivs: bool = False,
        subfield: str = 'arr', quick: dict | None = None,
        frame: Frame | str | None = 'J2000') -> tuple[Scalar, Scalar]: ...

class Fittable(Oops):
    @property
    def is_frozen(self) -> bool: ...
    @property
    def version(self) -> int: ...
    def set_params(self, params: float | Iterable[float]) -> bool: ...
    def refresh(self) -> bool: ...
    def copy(self) -> Fittable: ...
    def freeze(self) -> bool: ...

class Meshgrid(Oops):
    fov: FOV
    uv: Pair
    uv_w_duv_duv: Pair
    shape: tuple[int, ...]
    center_uv: Pair
    center_uv_w_duv_duv: Pair
    def __init__(self, fov: FOV, uv_pair: PairLike, center_uv: PairLike | None = None, *,
        fov_kwargs: dict | None = None) -> None: ...
    @staticmethod
    def for_fov(fov: FOV, origin: PairLike | None = None, undersample: PairLike = 1,
        oversample: PairLike = 1, limit: PairLike | None = None, swap: bool = False,
        fov_kwargs: dict | None = None) -> Meshgrid: ...
    @staticmethod
    def for_fov_center(fov: FOV, origin: PairLike | None = None,
        fov_kwargs: dict | None = None) -> Meshgrid: ...
    @staticmethod
    def for_shape(fov: FOV, shape: tuple[int, ...], u_axis: int = -1, v_axis: int = -1,
        origin: PairLike | None = None, undersample: PairLike = 1,
        oversample: PairLike = 1, limit: PairLike | None = None,
        center_uv: PairLike | None = None,
        fov_kwargs: dict | None = None) -> Meshgrid: ...
    def los_w_derivs(self, time: ScalarLike | None = None) -> Vector3: ...
    def los(self, time: ScalarLike | None = None) -> Vector3: ...
    def dlos_duv(self, time: ScalarLike | None = None) -> Vector3: ...
    def uv_w_derivs(self, time: ScalarLike | None = None) -> Pair: ...
    def duv_dlos(self, time: ScalarLike | None = None) -> Pair: ...
    def center_los_w_derivs(self, time: ScalarLike | None = None) -> Vector3: ...
    def center_los(self, time: ScalarLike | None = None) -> Vector3: ...
    def center_dlos_duv(self, time: ScalarLike | None = None) -> Vector3: ...
    def center_uv_w_derivs(self, time: ScalarLike | None = None) -> Pair: ...
    def center_duv_dlos(self, time: ScalarLike | None = None) -> Pair: ...

class Transform(Oops):
    matrix: Matrix3
    omega: Vector3
    is_fixed: bool
    frame: Frame
    reference: Frame
    origin: Path | None
    def __init__(self, matrix: Matrix3Like, omega: Vector3Like, frame: Frame | str,
        reference: Frame | str, *, origin: Path | str | None = None) -> None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def omega1(self) -> Vector3: ...
    @property
    def matrix_with_deriv(self) -> Matrix3: ...
    @property
    def inverse_matrix(self) -> Matrix3: ...
    @property
    def inverse_with_deriv(self) -> Matrix3: ...
    @property
    def wod(self) -> Transform: ...
    @staticmethod
    def identity(frame: Frame | str) -> Transform: ...
    def rotate(self, pos: Vector3Like | VectorLike | MatrixLike,
        derivs: bool = True) -> Vector3 | Vector | Matrix | None: ...
    def rotate_pos_vel(self, pos: Vector3Like,
        vel: Vector3Like) -> tuple[Vector3, Vector3]: ...
    def unrotate(self, pos: Vector3Like | VectorLike | MatrixLike,
        derivs: bool = True) -> Vector3 | Vector | Matrix | None: ...
    def unrotate_pos_vel(self, pos: Vector3Like,
        vel: Vector3Like) -> tuple[Vector3, Vector3]: ...
    def invert(self) -> Transform: ...
    def rotate_transform(self, arg: Transform) -> Transform: ...
    def unrotate_transform(self, arg: Transform) -> Transform: ...
    IDENTITY: Transform

C: float

C_INVERSE: float

RPD: float

DPR: float

SPR: float

RPS: float

SPD: float

AU: float

PI: float

TWOPI: float

HALFPI: float

##########################################################################################
