##########################################################################################
# oops/event.pyi
##########################################################################################
"""Type stub for :mod:`oops.event`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. The stub describes the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

from oops.config import EVENT_CONFIG as EVENT_CONFIG, LOGGING as LOGGING
from oops.constants import C_INVERSE as C_INVERSE
from oops.frame.frame_ import Frame as Frame
from oops.oops import Oops as Oops
from oops.transform import Transform as Transform

class Event(Oops):
    SSB: Any
    ARR_VEC3_PROPERTIES: Any
    DEP_VEC3_PROPERTIES: Any
    SPECIAL_PROPERTIES: Any
    def __init__(self, time: Any, state: Any, origin: Any, frame: Any = None,
        **more: Any) -> None: ...
    @property
    def time(self) -> Any: ...
    @property
    def state(self) -> Any: ...
    @property
    def pos(self) -> Any: ...
    @property
    def vel(self) -> Any: ...
    @property
    def origin(self) -> Any: ...
    @property
    def origin_id(self) -> Any: ...
    @property
    def frame(self) -> Any: ...
    @property
    def frame_id(self) -> Any: ...
    @property
    def subfields(self) -> Any: ...
    @property
    def shape(self) -> Any: ...
    @property
    def size(self) -> Any: ...
    @property
    def mask(self) -> Any: ...
    @property
    def antimask(self) -> Any: ...
    @property
    def ssb(self) -> Any: ...
    @property
    def xform_to_j2000(self) -> Any: ...
    @property
    def wod(self) -> Any: ...
    def empty_cache(self) -> None: ...
    def has_arrivals(self) -> Any: ...
    def has_departures(self) -> Any: ...
    @property
    def arr(self) -> Any: ...
    @arr.setter
    def arr(self, value: Any) -> None: ...
    @property
    def arr_ap(self) -> Any: ...
    @arr_ap.setter
    def arr_ap(self, value: Any) -> None: ...
    @property
    def arr_j2000(self) -> Any: ...
    @arr_j2000.setter
    def arr_j2000(self, value: Any) -> None: ...
    @property
    def arr_ap_j2000(self) -> Any: ...
    @arr_ap_j2000.setter
    def arr_ap_j2000(self, value: Any) -> None: ...
    @property
    def arr_lt(self) -> Any: ...
    @arr_lt.setter
    def arr_lt(self, value: Any) -> None: ...
    @property
    def neg_arr(self) -> Any: ...
    @neg_arr.setter
    def neg_arr(self, value: Any) -> None: ...
    @property
    def neg_arr_ap(self) -> Any: ...
    @neg_arr_ap.setter
    def neg_arr_ap(self, value: Any) -> None: ...
    @property
    def neg_arr_j2000(self) -> Any: ...
    @neg_arr_j2000.setter
    def neg_arr_j2000(self, value: Any) -> None: ...
    @property
    def neg_arr_ap_j2000(self) -> Any: ...
    @neg_arr_ap_j2000.setter
    def neg_arr_ap_j2000(self, value: Any) -> None: ...
    @property
    def dep(self) -> Any: ...
    @dep.setter
    def dep(self, value: Any) -> None: ...
    @property
    def dep_ap(self) -> Any: ...
    @dep_ap.setter
    def dep_ap(self, value: Any) -> None: ...
    @property
    def dep_j2000(self) -> Any: ...
    @dep_j2000.setter
    def dep_j2000(self, value: Any) -> None: ...
    @property
    def dep_ap_j2000(self) -> Any: ...
    @dep_ap_j2000.setter
    def dep_ap_j2000(self, value: Any) -> None: ...
    @property
    def dep_lt(self) -> Any: ...
    @dep_lt.setter
    def dep_lt(self, value: Any) -> None: ...
    @property
    def perp(self) -> Any: ...
    @perp.setter
    def perp(self, value: Any) -> None: ...
    @property
    def vflat(self) -> Any: ...
    @vflat.setter
    def vflat(self, value: Any) -> None: ...
    def insert_subfield(self, name: Any, value: Any) -> None: ...
    def get_subfield(self, name: Any) -> Any: ...
    def copy(self, omit: Any = ()) -> Any: ...
    def without_derivs(self) -> Any: ...
    def as_all_masked(self, origin: Any = None, frame: Any = None, *,
        broadcast: Any = None) -> Any: ...
    def mask_where(self, mask: Any) -> Any: ...
    def remask(self, mask: Any) -> Any: ...
    def replace(self, *args: Any) -> Any: ...
    def with_time_derivs(self) -> Any: ...
    def with_los_derivs(self) -> Any: ...
    def with_pos_derivs(self) -> Any: ...
    def with_lt_derivs(self) -> Any: ...
    def with_dep_derivs(self) -> Any: ...
    def with_dlt_derivs(self) -> Any: ...
    def shrink(self, antimask: Any) -> Any: ...
    def unshrink(self, antimask: Any, *, shape: Any = None) -> Any: ...
    def wrt_ssb(self, *, derivs: bool = True, quick: Any = None) -> Any: ...
    def from_ssb(self, path: Any, frame: Any, *, derivs: bool = True,
        quick: Any = None) -> Any: ...
    def wrt(self, path: Any = None, frame: Any = None, *, derivs: bool = True,
        quick: Any = None, include_xform: bool = False) -> Any: ...
    def wrt_path(self, path: Any, *, derivs: bool = True, quick: Any = None) -> Any: ...
    def wrt_frame(self, frame: Any, *, derivs: bool = True, quick: Any = None,
        include_xform: bool = False) -> Any: ...
    def rotate_by_frame(self, frame: Any, *, derivs: bool = True, quick: Any = None,
        include_xform: bool = False) -> Any: ...
    def unrotate_by_frame(self, frame: Any, *, derivs: bool = True,
        quick: Any = None) -> Any: ...
    def collapse_time(self, threshold: Any = None) -> Any: ...
    def sub(self, reference: Any, *, quick: Any = None) -> Any: ...
    def apparent_ray_ssb(self, ray_ssb: Any, *, derivs: bool = False,
        quick: Any = None) -> Any: ...
    def actual_ray_ssb(self, ray_ap_ssb: Any, *, derivs: bool = False,
        quick: Any = None) -> Any: ...
    def apparent_arr(self, *, derivs: bool = False, quick: Any = None) -> Any: ...
    def actual_arr(self, *, derivs: bool = False, quick: Any = None) -> Any: ...
    def apparent_dep(self, *, derivs: bool = False, quick: Any = None) -> Any: ...
    def actual_dep(self, *, derivs: bool = False, quick: Any = None) -> Any: ...
    def incidence_angle(self, apparent: bool = False, *, derivs: bool = False,
        quick: Any = None) -> Any: ...
    def emission_angle(self, apparent: bool = False, *, derivs: bool = False,
        quick: Any = None) -> Any: ...
    def phase_angle(self, apparent: bool = False, *, derivs: bool = False,
        quick: Any = None) -> Any: ...
    def ra_and_dec(self, apparent: bool = False, *, derivs: bool = False,
        subfield: str = 'arr', quick: Any = None, frame: str = 'J2000') -> Any: ...

##########################################################################################
