##########################################################################################
# oops/meshgrid.pyi
##########################################################################################
"""Type stub for :mod:`oops.meshgrid`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. The stub describes the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

from oops.oops import Oops as Oops

class Meshgrid(Oops):
    fov: Any
    uv: Any
    uv_w_duv_duv: Any
    shape: Any
    center_uv: Any
    center_uv_w_duv_duv: Any
    def __init__(self, fov: Any, uv_pair: Any, center_uv: Any = None, *,
        fov_kwargs: Any = None) -> None: ...
    @staticmethod
    def for_fov(fov: Any, origin: Any = None, undersample: int = 1, oversample: int = 1,
        limit: Any = None, swap: bool = False, fov_kwargs: Any = None) -> Any: ...
    @staticmethod
    def for_fov_center(fov: Any, origin: Any = None, fov_kwargs: Any = None) -> Any: ...
    @staticmethod
    def for_shape(fov: Any, shape: Any, u_axis: int = -1, v_axis: int = -1,
        origin: Any = None, undersample: int = 1, oversample: int = 1, limit: Any = None,
        center_uv: Any = None, fov_kwargs: Any = None) -> Any: ...
    def los_w_derivs(self, time: Any = None) -> Any: ...
    def los(self, time: Any = None) -> Any: ...
    def dlos_duv(self, time: Any = None) -> Any: ...
    def uv_w_derivs(self, time: Any = None) -> Any: ...
    def duv_dlos(self, time: Any = None) -> Any: ...
    def center_los_w_derivs(self, time: Any = None) -> Any: ...
    def center_los(self, time: Any = None) -> Any: ...
    def center_dlos_duv(self, time: Any = None) -> Any: ...
    def center_uv_w_derivs(self, time: Any = None) -> Any: ...
    def center_duv_dlos(self, time: Any = None) -> Any: ...

##########################################################################################
