##########################################################################################
# oops/transform.pyi
##########################################################################################
"""Type stub for :mod:`oops.transform`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. The stub describes the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

from oops.oops import Oops as Oops

class Transform(Oops):
    matrix: Any
    omega: Any
    is_fixed: Any
    frame: Any
    reference: Any
    origin: Any
    def __init__(self, matrix: Any, omega: Any, frame: Any, reference: Any, *,
        origin: Any = None) -> None: ...
    @property
    def shape(self) -> Any: ...
    @property
    def omega1(self) -> Any: ...
    @property
    def matrix_with_deriv(self) -> Any: ...
    @property
    def inverse_matrix(self) -> Any: ...
    @property
    def inverse_with_deriv(self) -> Any: ...
    @property
    def wod(self) -> Any: ...
    @staticmethod
    def identity(frame: Any) -> Any: ...
    def rotate(self, pos: Any, derivs: bool = True) -> Any: ...
    def rotate_pos_vel(self, pos: Any, vel: Any) -> Any: ...
    def unrotate(self, pos: Any, derivs: bool = True) -> Any: ...
    def unrotate_pos_vel(self, pos: Any, vel: Any) -> Any: ...
    def invert(self) -> Any: ...
    def rotate_transform(self, arg: Any) -> Any: ...
    def unrotate_transform(self, arg: Any) -> Any: ...
    IDENTITY: Transform

##########################################################################################
