##########################################################################################
# oops/backplane/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops.backplane`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. Only package stubs exist, so a name is annotated when it is
imported from the package that exports it and not when it is imported from the module
that defines it. The stub describes the shape of the API exactly: every public name, its
parameters, which of them are keyword-only, and which have defaults. Types are given
where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any
from oops import (Body as Body, Event as Event, Meshgrid as Meshgrid,
                  Observation as Observation, Surface as Surface)
from numpy import ndarray, number
from polymath import Qube, Scalar
from oops.mutable import Mutable as Mutable

# Parameters documented as a polymath type are passed through `as_scalar` and its
# siblings, so each accepts the class, a number, or a nested sequence of numbers.
# `str` is excluded deliberately: no polymath constructor accepts one.
_Numeric = float | number | list['_Numeric'] | tuple['_Numeric', ...]
ScalarLike = Scalar | ndarray | _Numeric

QubeLike = Qube | ndarray | _Numeric

__all__ = ['Backplane']

class Backplane(Mutable):
    _DIAGNOSTICS: bool
    _PERFORMANCE: bool
    _ALL_DERIVS: bool
    obs: Any
    meshgrid: Any
    inventory: Any
    _inventory_border: Any
    def __init__(self, obs: Observation, meshgrid: Meshgrid | None = None,
        time: ScalarLike | None = None, *, inventory: bool | dict | None = None,
        inventory_border: int = 0) -> None: ...
    @property
    def dlos_duv(self) -> Any: ...
    @property
    def dlos_duv1(self) -> Any: ...
    @property
    def duv_dlos(self) -> Any: ...
    @property
    def center_dlos_duv(self) -> Any: ...
    @property
    def center_duv_dlos(self) -> Any: ...
    @staticmethod
    def standardize_event_key(event_key: str | tuple, default: str = '') -> tuple: ...
    @staticmethod
    def gridless_event_key(event_key: str | tuple, default: str = '') -> tuple: ...
    def standardize_backplane_key(self,
        backplane_key: str | tuple | QubeLike) -> tuple: ...
    @staticmethod
    def _get_body_and_modifier(surface_key: str) -> tuple: ...
    @staticmethod
    def _unmasked_surface_key(surface_key: str) -> str: ...
    @staticmethod
    def _unmasked_event_key(event_key: str | tuple) -> tuple: ...
    @staticmethod
    def _intercept_dict_key(event_key: str | tuple) -> tuple: ...
    def get_obs_event(self, event_key: str | tuple, derivs: bool = False) -> Event: ...
    @staticmethod
    def get_surface(surface_key: str) -> Surface: ...
    def get_antimask(self, surface_key: str) -> ndarray | bool: ...
    def get_surface_event(self, event_key: str | tuple, derivs: bool = False,
        arrivals: bool = False) -> Event: ...
    def get_gridless_event(self, event_key: str | tuple, derivs: bool = False,
        arrivals: bool = False) -> Event: ...
    def register_backplane(self, key: tuple, backplane: QubeLike | ndarray | bool,
        expand: bool = False, derivs: bool = False) -> Qube: ...
    def get_backplane(self, key: tuple, derivs: bool = False) -> Qube: ...
    _CALLABLES: Any
    def evaluate(self, backplane_key: str | tuple, derivs: bool = False) -> Qube: ...
    def ansa_altitude(self, event_key: str | tuple) -> Any: ...
    def ansa_longitude(self, event_key: str | tuple, reference: str = 'node') -> Any: ...
    def ansa_radial_resolution(self, event_key: str | tuple) -> Any: ...
    def ansa_radius(self, event_key: str | tuple, radius_type: str = 'positive',
        rmax: Any = None) -> Any: ...
    def ansa_vertical_resolution(self, event_key: str | tuple) -> Any: ...
    def body_diameter_in_pixels(self, event_key: str | tuple, radius: float = 0,
        axis: str = 'max') -> Any: ...
    def border_above(self, backplane_key: str | tuple,
        value: float | ScalarLike) -> Any: ...
    def border_atop(self, backplane_key: str | tuple,
        value: float | ScalarLike) -> Any: ...
    def border_below(self, backplane_key: str | tuple,
        value: float | ScalarLike) -> Any: ...
    def border_inside(self, backplane_key: str | tuple) -> Any: ...
    def border_outside(self, backplane_key: str | tuple) -> Any: ...
    def celestial_east_angle(self, event_key: str | tuple = ()) -> Any: ...
    def celestial_north_angle(self, event_key: str | tuple = ()) -> Any: ...
    def center_coordinate(self, event_key: str | tuple, axis: str = 'u') -> Any: ...
    def center_declination(self, event_key: str | tuple, apparent: bool = True,
        direction: str = 'arr') -> Any: ...
    def center_distance(self, event_key: str | tuple, direction: str = 'dep') -> Any: ...
    def center_emission_angle(self, event_key: str | tuple,
        apparent: bool = True) -> Any: ...
    def center_incidence_angle(self, event_key: str | tuple,
        apparent: bool = True) -> Any: ...
    def center_light_time(self, event_key: str | tuple,
        direction: str = 'dep') -> Any: ...
    def center_phase_angle(self, event_key: str | tuple,
        apparent: bool = True) -> Any: ...
    def center_resolution(self, event_key: str | tuple, axis: str = 'u') -> Any: ...
    def center_right_ascension(self, event_key: str | tuple, apparent: bool = True,
        direction: str = 'arr') -> Any: ...
    def center_scattering_angle(self, event_key: str | tuple,
        apparent: bool = True) -> Any: ...
    def center_time(self, event_key: str | tuple) -> Any: ...
    def coarsest_resolution(self, event_key: str | tuple) -> Any: ...
    def declination(self, event_key: str | tuple = (), apparent: bool = True,
        direction: str = 'arr') -> Any: ...
    def distance(self, event_key: str | tuple, direction: str = 'dep') -> Any: ...
    def emission_angle(self, event_key: str | tuple, apparent: bool = True) -> Any: ...
    def event_time(self, event_key: str | tuple) -> Any: ...
    def finest_resolution(self, event_key: str | tuple) -> Any: ...
    def incidence_angle(self, event_key: str | tuple, apparent: bool = True) -> Any: ...
    def lambert_law(self, event_key: str | tuple) -> Any: ...
    def latitude(self, event_key: str | tuple, lat_type: str = 'centric') -> Any: ...
    def light_time(self, event_key: str | tuple, direction: str = 'dep') -> Any: ...
    def limb_altitude(self, event_key: str | tuple, zmin: Any = None, zmax: Any = None,
        scaled: bool = False) -> Any: ...
    def limb_clock_angle(self, event_key: str | tuple) -> Any: ...
    def limb_latitude(self, event_key: str | tuple, lat_type: str = 'centric') -> Any: ...
    def limb_longitude(self, event_key: str | tuple, reference: str = 'iau',
        direction: str = 'west', minimum: float = 0,
        lon_type: str = 'centric') -> Any: ...
    def lommel_seeliger_law(self, event_key: str | tuple) -> Any: ...
    def longitude(self, event_key: str | tuple, reference: str = 'iau',
        direction: str = 'west', minimum: float = 0,
        lon_type: str = 'centric') -> Any: ...
    def minnaert_law(self, event_key: str | tuple, k: float, k2: float | None = None,
        clip: float = 0.2) -> Any: ...
    def mu(self, event_key: str | tuple, apparent: bool = True) -> Any: ...
    def mu0(self, event_key: str | tuple, apparent: bool = True) -> Any: ...
    def orbit_longitude(self, event_key: str | tuple, reference: str = 'obs',
        planet: Any = None) -> Any: ...
    def phase_angle(self, event_key: str | tuple, apparent: bool = True) -> Any: ...
    def pole_clock_angle(self, event_key: str | tuple) -> Any: ...
    def pole_position_angle(self, event_key: str | tuple) -> Any: ...
    def radial_mode(self, backplane_key: str | tuple, cycles: float, epoch: float,
        amp: float, peri0: float, speed: float, a0: float = 0.0, dperi_da: float = 0.0,
        reference: str = 'node') -> Any: ...
    def resolution(self, event_key: str | tuple, axis: str = 'u') -> Any: ...
    def right_ascension(self, event_key: str | tuple = (), apparent: bool = True,
        direction: str = 'arr') -> Any: ...
    def ring_angular_resolution(self, event_key: str | tuple,
        units: str = 'rad') -> Any: ...
    def ring_azimuth(self, event_key: str | tuple, direction: str = 'obs',
        apparent: bool = True) -> Any: ...
    def ring_center_emission_angle(self, event_key: str | tuple, pole: str = 'sunward',
        apparent: bool = True) -> Any: ...
    def ring_center_incidence_angle(self, event_key: str | tuple, pole: str = 'sunward',
        apparent: bool = True) -> Any: ...
    def ring_elevation(self, event_key: str | tuple, direction: str = 'obs',
        pole: str = 'prograde', apparent: bool = True) -> Any: ...
    def ring_emission_angle(self, event_key: str | tuple, pole: str = 'sunward',
        apparent: bool = True) -> Any: ...
    def ring_gradient_angle(self, event_key: str | tuple) -> Any: ...
    def ring_incidence_angle(self, event_key: str | tuple, pole: str = 'sunward',
        apparent: bool = True) -> Any: ...
    def ring_longitude(self, event_key: str | tuple, reference: str = 'node') -> Any: ...
    def ring_radial_resolution(self, event_key: str | tuple) -> Any: ...
    def ring_radius(self, event_key: str | tuple, rmin: Any = None,
        rmax: Any = None) -> Any: ...
    def ring_radius_in_front(self, event_key: str | tuple,
        ring_surface_key: str) -> Any: ...
    def ring_shadow_incidence(self, event_key: str | tuple,
        ring_surface_key: str) -> Any: ...
    def ring_shadow_radius(self, event_key: str | tuple,
        ring_surface_key: str) -> Any: ...
    def ring_sub_observer_longitude(self, event_key: str | tuple,
        reference: str = 'node') -> Any: ...
    def ring_sub_solar_longitude(self, event_key: str | tuple,
        reference: str = 'node') -> Any: ...
    def scattering_angle(self, event_key: str | tuple, apparent: bool = True) -> Any: ...
    def sub_observer_latitude(self, event_key: str | tuple,
        lat_type: str = 'centric') -> Any: ...
    def sub_observer_longitude(self, event_key: str | tuple, reference: str = 'iau',
        direction: str = 'west', minimum: float = 0) -> Any: ...
    def sub_solar_latitude(self, event_key: str | tuple,
        lat_type: str = 'centric') -> Any: ...
    def sub_solar_longitude(self, event_key: str | tuple, reference: str = 'iau',
        direction: str = 'west', minimum: float = 0) -> Any: ...
    def where_above(self, backplane_key: str | tuple, value: float | ScalarLike,
        tvl: bool = False) -> Any: ...
    def where_all(self, *backplane_keys: str | tuple, tvl: bool = False) -> Any: ...
    def where_antisunward(self, event_key: str | tuple, tvl: bool = False) -> Any: ...
    def where_any(self, *backplane_keys: str | tuple, tvl: bool = False) -> Any: ...
    def where_below(self, backplane_key: str | tuple, value: float | ScalarLike,
        tvl: bool = False) -> Any: ...
    def where_between(self, backplane_key: str | tuple, low: float | ScalarLike,
        high: float | ScalarLike, tvl: bool = False) -> Any: ...
    def where_in_back(self, event_key: str | tuple, surface_key: str,
        tvl: bool = False) -> Any: ...
    def where_in_front(self, event_key: str | tuple, surface_key: str,
        tvl: bool = False) -> Any: ...
    def where_inside(self, event_key: str | tuple, surface_key: str,
        tvl: bool = False) -> Any: ...
    def where_inside_shadow(self, event_key: str | tuple, surface_key: str,
        tvl: bool = False) -> Any: ...
    def where_intercepted(self, event_key: str | tuple) -> Any: ...
    def where_not(self, backplane_key: str | tuple, tvl: bool = False) -> Any: ...
    def where_outside(self, event_key: str | tuple, surface_key: str,
        tvl: bool = False) -> Any: ...
    def where_outside_shadow(self, event_key: str | tuple, surface_key: str,
        tvl: bool = False) -> Any: ...
    def where_sunward(self, event_key: str | tuple, tvl: bool = False) -> Any: ...

##########################################################################################
