##########################################################################################
# oops/backplane/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops.backplane`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. The stub describes the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

from oops.mutable import Mutable

__all__ = ['Backplane']

class Backplane(Mutable):
    _DIAGNOSTICS: bool
    _PERFORMANCE: bool
    _ALL_DERIVS: bool
    obs: Any
    meshgrid: Any
    inventory: Any
    _inventory_border: Any
    def __init__(self, obs: Any, meshgrid: Any = None, time: Any = None, *,
        inventory: Any = None, inventory_border: int = 0) -> None: ...
    @property
    def dlos_duv(self) -> Any: ...
    @property
    def dlos_duv1(self) -> Any: ...
    @property
    def duv_dlos(self) -> Any: ...
    @property
    def center_dlos_duv(self) -> Any: ...
    @property
    def center_duv_dlos(self) -> Any: ...
    @staticmethod
    def standardize_event_key(event_key: Any, default: str = '') -> Any: ...
    @staticmethod
    def gridless_event_key(event_key: Any, default: str = '') -> Any: ...
    def standardize_backplane_key(self, backplane_key: Any) -> Any: ...
    @staticmethod
    def _get_body_and_modifier(surface_key: Any) -> Any: ...
    @staticmethod
    def _unmasked_surface_key(surface_key: Any) -> Any: ...
    @staticmethod
    def _unmasked_event_key(event_key: Any) -> Any: ...
    @staticmethod
    def _intercept_dict_key(event_key: Any) -> Any: ...
    def get_obs_event(self, event_key: Any, derivs: bool = False) -> Any: ...
    @staticmethod
    def get_surface(surface_key: Any) -> Any: ...
    def get_antimask(self, surface_key: Any) -> Any: ...
    def get_surface_event(self, event_key: Any, derivs: bool = False,
        arrivals: bool = False) -> Any: ...
    def get_gridless_event(self, event_key: Any, derivs: bool = False,
        arrivals: bool = False) -> Any: ...
    def register_backplane(self, key: Any, backplane: Any, expand: bool = False,
        derivs: bool = False) -> Any: ...
    def get_backplane(self, key: Any, derivs: bool = False) -> Any: ...
    _CALLABLES: Any
    def evaluate(self, backplane_key: Any, derivs: bool = False) -> Any: ...
    def ansa_altitude(self, event_key: Any) -> Any: ...
    def ansa_longitude(self, event_key: Any, reference: str = 'node') -> Any: ...
    def ansa_radial_resolution(self, event_key: Any) -> Any: ...
    def ansa_radius(self, event_key: Any, radius_type: str = 'positive',
        rmax: Any = None) -> Any: ...
    def ansa_vertical_resolution(self, event_key: Any) -> Any: ...
    def body_diameter_in_pixels(self, event_key: Any, radius: int = 0,
        axis: str = 'max') -> Any: ...
    def border_above(self, backplane_key: Any, value: Any) -> Any: ...
    def border_atop(self, backplane_key: Any, value: Any) -> Any: ...
    def border_below(self, backplane_key: Any, value: Any) -> Any: ...
    def border_inside(self, backplane_key: Any) -> Any: ...
    def border_outside(self, backplane_key: Any) -> Any: ...
    def celestial_east_angle(self, event_key: Any = ()) -> Any: ...
    def celestial_north_angle(self, event_key: Any = ()) -> Any: ...
    def center_coordinate(self, event_key: Any, axis: str = 'u') -> Any: ...
    def center_declination(self, event_key: Any, apparent: bool = True,
        direction: str = 'arr') -> Any: ...
    def center_distance(self, event_key: Any, direction: str = 'dep') -> Any: ...
    def center_emission_angle(self, event_key: Any, apparent: bool = True) -> Any: ...
    def center_incidence_angle(self, event_key: Any, apparent: bool = True) -> Any: ...
    def center_light_time(self, event_key: Any, direction: str = 'dep') -> Any: ...
    def center_phase_angle(self, event_key: Any, apparent: bool = True) -> Any: ...
    def center_resolution(self, event_key: Any, axis: str = 'u') -> Any: ...
    def center_right_ascension(self, event_key: Any, apparent: bool = True,
        direction: str = 'arr') -> Any: ...
    def center_scattering_angle(self, event_key: Any, apparent: bool = True) -> Any: ...
    def center_time(self, event_key: Any) -> Any: ...
    def coarsest_resolution(self, event_key: Any) -> Any: ...
    def declination(self, event_key: Any = (), apparent: bool = True,
        direction: str = 'arr') -> Any: ...
    def distance(self, event_key: Any, direction: str = 'dep') -> Any: ...
    def emission_angle(self, event_key: Any, apparent: bool = True) -> Any: ...
    def event_time(self, event_key: Any) -> Any: ...
    def finest_resolution(self, event_key: Any) -> Any: ...
    def incidence_angle(self, event_key: Any, apparent: bool = True) -> Any: ...
    def lambert_law(self, event_key: Any) -> Any: ...
    def latitude(self, event_key: Any, lat_type: str = 'centric') -> Any: ...
    def light_time(self, event_key: Any, direction: str = 'dep') -> Any: ...
    def limb_altitude(self, event_key: Any, zmin: Any = None, zmax: Any = None,
        scaled: bool = False) -> Any: ...
    def limb_clock_angle(self, event_key: Any) -> Any: ...
    def limb_latitude(self, event_key: Any, lat_type: str = 'centric') -> Any: ...
    def limb_longitude(self, event_key: Any, reference: str = 'iau',
        direction: str = 'west', minimum: int = 0, lon_type: str = 'centric') -> Any: ...
    def lommel_seeliger_law(self, event_key: Any) -> Any: ...
    def longitude(self, event_key: Any, reference: str = 'iau', direction: str = 'west',
        minimum: int = 0, lon_type: str = 'centric') -> Any: ...
    def minnaert_law(self, event_key: Any, k: Any, k2: Any = None,
        clip: float = 0.2) -> Any: ...
    def mu(self, event_key: Any, apparent: bool = True) -> Any: ...
    def mu0(self, event_key: Any, apparent: bool = True) -> Any: ...
    def orbit_longitude(self, event_key: Any, reference: str = 'obs',
        planet: Any = None) -> Any: ...
    def phase_angle(self, event_key: Any, apparent: bool = True) -> Any: ...
    def pole_clock_angle(self, event_key: Any) -> Any: ...
    def pole_position_angle(self, event_key: Any) -> Any: ...
    def radial_mode(self, backplane_key: Any, cycles: Any, epoch: Any, amp: Any,
        peri0: Any, speed: Any, a0: float = 0.0, dperi_da: float = 0.0,
        reference: str = 'node') -> Any: ...
    def resolution(self, event_key: Any, axis: str = 'u') -> Any: ...
    def right_ascension(self, event_key: Any = (), apparent: bool = True,
        direction: str = 'arr') -> Any: ...
    def ring_angular_resolution(self, event_key: Any, units: str = 'rad') -> Any: ...
    def ring_azimuth(self, event_key: Any, direction: str = 'obs',
        apparent: bool = True) -> Any: ...
    def ring_center_emission_angle(self, event_key: Any, pole: str = 'sunward',
        apparent: bool = True) -> Any: ...
    def ring_center_incidence_angle(self, event_key: Any, pole: str = 'sunward',
        apparent: bool = True) -> Any: ...
    def ring_elevation(self, event_key: Any, direction: str = 'obs',
        pole: str = 'prograde', apparent: bool = True) -> Any: ...
    def ring_emission_angle(self, event_key: Any, pole: str = 'sunward',
        apparent: bool = True) -> Any: ...
    def ring_gradient_angle(self, event_key: Any) -> Any: ...
    def ring_incidence_angle(self, event_key: Any, pole: str = 'sunward',
        apparent: bool = True) -> Any: ...
    def ring_longitude(self, event_key: Any, reference: str = 'node') -> Any: ...
    def ring_radial_resolution(self, event_key: Any) -> Any: ...
    def ring_radius(self, event_key: Any, rmin: Any = None, rmax: Any = None) -> Any: ...
    def ring_radius_in_front(self, event_key: Any, ring_surface_key: Any) -> Any: ...
    def ring_shadow_incidence(self, event_key: Any, ring_surface_key: Any) -> Any: ...
    def ring_shadow_radius(self, event_key: Any, ring_surface_key: Any) -> Any: ...
    def ring_sub_observer_longitude(self, event_key: Any,
        reference: str = 'node') -> Any: ...
    def ring_sub_solar_longitude(self, event_key: Any,
        reference: str = 'node') -> Any: ...
    def scattering_angle(self, event_key: Any, apparent: bool = True) -> Any: ...
    def sub_observer_latitude(self, event_key: Any, lat_type: str = 'centric') -> Any: ...
    def sub_observer_longitude(self, event_key: Any, reference: str = 'iau',
        direction: str = 'west', minimum: int = 0) -> Any: ...
    def sub_solar_latitude(self, event_key: Any, lat_type: str = 'centric') -> Any: ...
    def sub_solar_longitude(self, event_key: Any, reference: str = 'iau',
        direction: str = 'west', minimum: int = 0) -> Any: ...
    def where_above(self, backplane_key: Any, value: Any, tvl: bool = False) -> Any: ...
    def where_all(self, *backplane_keys: Any, tvl: bool = False) -> Any: ...
    def where_antisunward(self, event_key: Any, tvl: bool = False) -> Any: ...
    def where_any(self, *backplane_keys: Any, tvl: bool = False) -> Any: ...
    def where_below(self, backplane_key: Any, value: Any, tvl: bool = False) -> Any: ...
    def where_between(self, backplane_key: Any, low: Any, high: Any,
        tvl: bool = False) -> Any: ...
    def where_in_back(self, event_key: Any, surface_key: Any,
        tvl: bool = False) -> Any: ...
    def where_in_front(self, event_key: Any, surface_key: Any,
        tvl: bool = False) -> Any: ...
    def where_inside(self, event_key: Any, surface_key: Any,
        tvl: bool = False) -> Any: ...
    def where_inside_shadow(self, event_key: Any, surface_key: Any,
        tvl: bool = False) -> Any: ...
    def where_intercepted(self, event_key: Any) -> Any: ...
    def where_not(self, backplane_key: Any, tvl: bool = False) -> Any: ...
    def where_outside(self, event_key: Any, surface_key: Any,
        tvl: bool = False) -> Any: ...
    def where_outside_shadow(self, event_key: Any, surface_key: Any,
        tvl: bool = False) -> Any: ...
    def where_sunward(self, event_key: Any, tvl: bool = False) -> Any: ...

##########################################################################################
