##########################################################################################
# oops/backplane/where.pyi
##########################################################################################
"""Type stub for :mod:`oops.backplane.where`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. The stub describes the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

from oops.backplane import Backplane as Backplane

def where_intercepted(self, event_key: Any) -> Any: ...

def where_inside_shadow(self, event_key: Any, surface_key: Any,
    tvl: bool = False) -> Any: ...

def where_outside_shadow(self, event_key: Any, surface_key: Any,
    tvl: bool = False) -> Any: ...

def where_in_front(self, event_key: Any, surface_key: Any, tvl: bool = False) -> Any: ...

def where_in_back(self, event_key: Any, surface_key: Any, tvl: bool = False) -> Any: ...

def where_sunward(self, event_key: Any, tvl: bool = False) -> Any: ...

def where_antisunward(self, event_key: Any, tvl: bool = False) -> Any: ...

def where_inside(self, event_key: Any, surface_key: Any, tvl: bool = False) -> Any: ...

def where_outside(self, event_key: Any, surface_key: Any, tvl: bool = False) -> Any: ...

def where_below(self, backplane_key: Any, value: Any, tvl: bool = False) -> Any: ...

def where_above(self, backplane_key: Any, value: Any, tvl: bool = False) -> Any: ...

def where_between(self, backplane_key: Any, low: Any, high: Any,
    tvl: bool = False) -> Any: ...

def where_not(self, backplane_key: Any, tvl: bool = False) -> Any: ...

def where_any(self, *backplane_keys: Any, tvl: bool = False) -> Any: ...

def where_all(self, *backplane_keys: Any, tvl: bool = False) -> Any: ...

##########################################################################################
