##########################################################################################
# oops/calibration/__init__.pyi
##########################################################################################
"""Type stub for :mod:`oops.calibration`.

The source types its methods in their docstrings rather than in their signatures, so the
type information for public symbols is published here instead. Only package stubs exist,
so a name is annotated when it is imported from the package that exports it and not when
it is imported from the module that defines it. The stub describes the shape of the API
exactly: every public name, its parameters, which of them are keyword-only, and which have
defaults. Types are given where they are unambiguous and are `Any` elsewhere.
"""

from oops import FOV as FOV
from polymath import Scalar
# Parameters documented as a polymath type are passed through `as_scalar` and its
# siblings, so each accepts the class, a number, or a nested sequence of numbers.
# `polymath.typedefs` names each of those unions.
from polymath.typedefs import PairLike, ScalarLike
from oops.oops import Oops as Oops

__all__ = ['Calibration', 'FlatCalib', 'NullCalib', 'Radiance', 'RawCounts']

class Calibration(Oops):
    def extended_from_dn(self, dn: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def dn_from_extended(self, value: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def point_from_dn(self, dn: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def dn_from_point(self, value: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def prescale(self, factor: ScalarLike, baseline: ScalarLike = 0.0, *,
        name: str = '') -> Calibration: ...
    def value_from_dn(self, dn: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def dn_from_value(self, value: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def area_factor(self, uv_pair: PairLike) -> Scalar: ...

class FlatCalib(Calibration):
    name: str
    has_baseline: bool
    shape: tuple[int, ...]
    fov: FOV | None
    def __init__(self, name: str, factor: ScalarLike, baseline: ScalarLike = 0.0,
        fov: FOV | None = None) -> None: ...
    def extended_from_dn(self, dn: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def dn_from_extended(self, value: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def point_from_dn(self, dn: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def dn_from_point(self, value: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def prescale(self, factor: ScalarLike, baseline: ScalarLike = 0.0, *,
        name: str = '') -> Calibration: ...

class NullCalib(Calibration):
    name: str
    factor: Scalar
    baseline: Scalar
    has_baseline: bool
    fov: FOV | None
    shape: tuple[int, ...]
    def __init__(self, name: str) -> None: ...
    def extended_from_dn(self, dn: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def dn_from_extended(self, value: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def point_from_dn(self, dn: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def dn_from_point(self, value: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def prescale(self, factor: ScalarLike, baseline: ScalarLike = 0.0, *,
        name: str = '') -> Calibration: ...

class Radiance(FlatCalib):
    name: str
    fov: FOV
    has_baseline: bool
    shape: tuple[int, ...]
    def __init__(self, name: str, fov: FOV | None, factor: ScalarLike,
        baseline: ScalarLike = 0.0) -> None: ...
    def point_from_dn(self, dn: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def dn_from_point(self, value: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def prescale(self, factor: ScalarLike, baseline: ScalarLike = 0.0, *,
        name: str = '') -> Calibration: ...

class RawCounts(FlatCalib):
    name: str
    fov: FOV
    has_baseline: bool
    shape: tuple[int, ...]
    def __init__(self, name: str, fov: FOV | None, factor: ScalarLike,
        baseline: ScalarLike = 0.0) -> None: ...
    def extended_from_dn(self, dn: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def dn_from_extended(self, value: ScalarLike, uv_pair: PairLike) -> Scalar: ...
    def prescale(self, factor: ScalarLike, baseline: ScalarLike = 0.0, *,
        name: str = '') -> Calibration: ...

##########################################################################################
