##########################################################################################
# oops/fov/fov_.pyi
##########################################################################################
"""Type stub for :mod:`oops.fov.fov_`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. The stub describes the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

from oops.config import AREA_FACTOR as AREA_FACTOR
from oops.mutable import Mutable as Mutable

class FOV(Mutable):
    IS_TIME_INDEPENDENT: bool
    def xy_from_uvt(self, uv_pair: Any, time: Any = None, *, derivs: bool = False,
        remask: bool = False, **kwargs: Any) -> Any: ...
    def uv_from_xyt(self, xy_pair: Any, time: Any = None, *, derivs: bool = False,
        remask: bool = False, **kwargs: Any) -> Any: ...
    def xy_from_uv(self, uv_pair: Any, *, derivs: bool = False, remask: bool = False,
        **kwargs: Any) -> Any: ...
    def uv_from_xy(self, xy_pair: Any, *, derivs: bool = False, remask: bool = False,
        **kwargs: Any) -> Any: ...
    def area_factor(self, uv_pair: Any, time: Any = None, *, remask: bool = False,
        **kwargs: Any) -> Any: ...
    def los_from_xy(self, xy_pair: Any, *, derivs: bool = False) -> Any: ...
    def xy_from_los(self, los: Any, *, derivs: bool = False) -> Any: ...
    def los_from_uvt(self, uv_pair: Any, time: Any = None, *, derivs: bool = False,
        remask: bool = False, **kwargs: Any) -> Any: ...
    def los_from_uv(self, uv_pair: Any, *, derivs: bool = False, remask: bool = False,
        **kwargs: Any) -> Any: ...
    def uv_from_los_t(self, los: Any, time: Any = None, *, derivs: bool = False,
        remask: bool = False, **kwargs: Any) -> Any: ...
    def uv_from_los(self, los: Any, *, derivs: bool = False, remask: bool = False,
        **kwargs: Any) -> Any: ...
    def offset_angles_from_duv(self, duv: Any, *, time: Any = None,
        origin: Any = None) -> Any: ...
    def offset_duv_from_angles(self, angles: Any, *, time: Any = None,
        origin: Any = None) -> Any: ...
    def uv_is_outside(self, uv_pair: Any, time: Any = None, *, uv_min: Any = None,
        uv_max: Any = None, inclusive: bool = True) -> Any: ...
    def u_or_v_is_outside(self, uv_pair: Any, uv_index: Any, *, uv_min: Any = None,
        uv_max: Any = None, inclusive: bool = True) -> Any: ...
    def xy_is_outside(self, xy_pair: Any, time: Any = None, *, inclusive: bool = True,
        uv_min: Any = None, uv_max: Any = None, **kwargs: Any) -> Any: ...
    def los_is_outside(self, los: Any, time: Any = None, *, inclusive: bool = True,
        uv_min: Any = None, uv_max: Any = None, **kwargs: Any) -> Any: ...
    def nearest_uv(self, uv_pair: Any, *, remask: bool = False) -> Any: ...
    def max_inversion_error(self, steps: int = 30) -> Any: ...
    def center_xy(self, time: Any = None) -> Any: ...
    def center_los(self, time: Any = None) -> Any: ...
    @property
    def center_dlos_duv(self) -> Any: ...
    @property
    def outer_radius(self) -> Any: ...
    @property
    def inner_radius(self) -> Any: ...
    def corner00_xy(self, time: Any = None) -> Any: ...
    def corner01_xy(self, time: Any = None) -> Any: ...
    def corner10_xy(self, time: Any = None) -> Any: ...
    def corner11_xy(self, time: Any = None) -> Any: ...
    def sphere_falls_inside(self, center: Any, radius: Any, *, time: Any = None,
        border: float = 0.0) -> Any: ...

##########################################################################################
