##########################################################################################
# oops/fov/nullfov.pyi
##########################################################################################
"""Type stub for :mod:`oops.fov.nullfov`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. The stub describes the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

from oops.fov import FOV as FOV

class NullFOV(FOV):
    uv_los: Any
    uv_scale: Any
    uv_shape: Any
    uv_area: float
    def __init__(self) -> None: ...
    def xy_from_uvt(self, uv_pair: Any, time: Any = None, *, derivs: bool = False,
        remask: bool = False, **kwargs: Any) -> Any: ...
    def uv_from_xyt(self, xy_pair: Any, time: Any = None, *, derivs: bool = False,
        remask: bool = False, **kwargs: Any) -> Any: ...
    def area_factor(self, uv_pair: Any, time: Any = None, *, remask: bool = False,
        **kwargs: Any) -> Any: ...
    def los_from_xy(self, xy_pair: Any, *, derivs: bool = False) -> Any: ...
    def xy_from_los(self, los: Any, *, derivs: bool = False) -> Any: ...
    def los_from_uvt(self, uv_pair: Any, time: Any = None, *, derivs: bool = False,
        remask: bool = False, **kwargs: Any) -> Any: ...
    def uv_from_los_t(self, los: Any, time: Any = None, *, derivs: bool = False,
        remask: bool = False, **kwargs: Any) -> Any: ...
    def uv_is_outside(self, uv_pair: Any, time: Any = None, *, uv_min: Any = None,
        uv_max: Any = None, inclusive: bool = True) -> Any: ...
    def u_or_v_is_outside(self, uv_pair: Any, uv_index: Any, *, uv_min: Any = None,
        uv_max: Any = None, inclusive: bool = True) -> Any: ...
    def xy_is_outside(self, xy_pair: Any, time: Any = None, *, inclusive: bool = True,
        uv_min: Any = None, uv_max: Any = None, **kwargs: Any) -> Any: ...
    def los_is_outside(self, los: Any, time: Any = None, *, inclusive: bool = True,
        uv_min: Any = None, uv_max: Any = None, **kwargs: Any) -> Any: ...
    def nearest_uv(self, uv_pair: Any, *, remask: bool = False) -> Any: ...
    def max_inversion_error(self, steps: int = 30) -> Any: ...

##########################################################################################
