##########################################################################################
# oops/observation/observation_.pyi
##########################################################################################
"""Type stub for :mod:`oops.observation.observation_`.

The `src` tree carries no inline annotations, so type information for public symbols is
published here instead. The stub describes the shape of the API exactly: every public
name, its parameters, which of them are keyword-only, and which have defaults. Types are
given where they are unambiguous and are `Any` elsewhere.
"""

from typing import Any

from oops import mutable as mutable
from oops.config import LOGGING as LOGGING, PATH_PHOTONS as PATH_PHOTONS
from oops.event import Event as Event
from oops.frame import Frame as Frame
from oops.frame.cmatrix import Cmatrix as Cmatrix
from oops.frame.navigation import Navigation as Navigation
from oops.meshgrid import Meshgrid as Meshgrid
from oops.mutable import Mutable as Mutable

class Observation(Mutable):
    def __init__(self) -> None: ...
    @property
    def time(self) -> Any: ...
    @property
    def midtime(self) -> Any: ...
    def uvt(self, indices: Any, *, remask: bool = False, derivs: bool = True) -> Any: ...
    def uvt_range(self, indices: Any, *, remask: bool = False) -> Any: ...
    def time_range_at_uv(self, uv_pair: Any, *, remask: bool = False) -> Any: ...
    def _time_range_at_uv_0d(self, uv_pair: Any, *, remask: bool = False) -> Any: ...
    def _time_range_at_uv_1d(self, uv_pair: Any, *, axis: int = 0,
        remask: bool = False) -> Any: ...
    def _time_range_at_uv_2d(self, uv_pair: Any, *, fast: int = 1,
        remask: bool = False) -> Any: ...
    def uv_range_at_time(self, time: Any, *, remask: bool = False) -> Any: ...
    def _uv_range_at_time_0d(self, time: Any, uv_shape: Any, *,
        remask: bool = False) -> Any: ...
    def _uv_range_at_time_1d(self, time: Any, uv_shape: Any, *, axis: int = 0,
        remask: bool = False) -> Any: ...
    def _uv_range_at_time_2d(self, time: Any, uv_shape: Any, *, slow: int = 0,
        fast: int = 1, remask: bool = False) -> Any: ...
    def uv_range_at_tstep(self, tstep: Any, *, remask: bool = False) -> Any: ...
    def _uv_range_at_tstep_0d(self, tstep: Any, uv_shape: Any, *,
        remask: bool = False) -> Any: ...
    def _uv_range_at_tstep_1d(self, tstep: Any, uv_shape: Any, *, axis: int = 0,
        remask: bool = False) -> Any: ...
    def _uv_range_at_tstep_2d(self, tstep: Any, uv_shape: Any, *, slow: int = 0,
        fast: int = 1, remask: bool = False) -> Any: ...
    def time_shift(self, dtime: Any) -> Any: ...
    def copy(self) -> Any: ...
    def navigate(self, angles: Any) -> Any: ...
    frame: Any
    def set_frame(self, frame: Any) -> None: ...
    def get_spice_cmatrix(self, tstep: Any = None, *, time: Any = None) -> Any: ...
    def set_spice_cmatrix(self, matrix: Any) -> None: ...
    def insert_subfield(self, key: Any, value: Any) -> None: ...
    def delete_subfield(self, key: Any) -> None: ...
    def delete_subfields(self) -> None: ...
    def uv_is_outside(self, uv_pair: Any, *, inclusive: bool = True) -> Any: ...
    def midtime_at_uv(self, uv: Any, *, tfrac: float = 0.5) -> Any: ...
    def meshgrid(self, origin: Any = None, *, undersample: int = 1, oversample: int = 1,
        limit: Any = None, center_uv: Any = None, fov_kwargs: Any = None) -> Any: ...
    def timegrid(self, meshgrid: Any, *, oversample: int = 1,
        tfrac_limits: Any = (0, 1)) -> Any: ...
    def event_at_grid(self, meshgrid: Any = None, *, tfrac: float = 0.5,
        time: Any = None) -> Any: ...
    def gridless_event(self, meshgrid: Any = None, *, tfrac: float = 0.5,
        time: Any = None, shapeless: bool = False) -> Any: ...
    @staticmethod
    def _scalar_from_indices(indices: Any, axis: Any, *, derivs: bool = True) -> Any: ...
    def uv_from_ra_and_dec(self, ra: Any, dec: Any, *, tfrac: float = 0.5,
        time: Any = None, apparent: bool = True, derivs: bool = False, iters: int = 2,
        quick: Any = None) -> Any: ...
    def uv_from_path(self, path: Any, *, tfrac: float = 0.5, time: Any = None,
        derivs: bool = False, guess: Any = None, quick: Any = None,
        converge: Any = None) -> Any: ...
    def uv_from_coords(self, surface: Any, coords: Any, *, tfrac: float = 0.5,
        time: Any = None, underside: bool = False, derivs: bool = False,
        quick: Any = None, converge: Any = None) -> Any: ...
    def inventory(self, bodies: Any, *, tfrac: Any = None, time: Any = None,
        expand: float = 0.0, return_type: str = 'list', fov: Any = None,
        quick: Any = None, converge: Any = None) -> Any: ...
    def parallel_los(self, parallel: Any, los: Any, *, time: Any = None,
        derivs: bool = False) -> Any: ...
    def parallel_uv(self, parallel: Any, uv: Any, *, time: Any = None,
        derivs: bool = False) -> Any: ...
    def parallel_offset_angles(self, parallel: Any, angles: Any, *,
        time: Any = None) -> Any: ...
    def parallel_offset_duv(self, parallel: Any, duv: Any, *, time: Any = None,
        origin: Any = None) -> Any: ...

##########################################################################################
